apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgAH8s45S+dBtt/OQPue7QAX3jWK1atY/AgDgfWam+VqRyFbVh+34bKomIxyskwRZFt753oNu5y4bjpk4v6DcUXbNrt4/vWrWxuN/CNya/WkjB8s6TZd7cCW+r97ZdWVBJ2uUKQCFNMVyzibu3Mg9V4z2ojaQWa375qTEULjuYBvJLV8IBncF5/Zyiro9AOGccchnxOisOEicTAyezDEviz9xjCARSoaggtzcow7ThHGAEUy8q+WW9uGfd11yOPC1jVIanvXyIIclbABYTLFcpde5vtvWDcer5fd00h35HvamftQnmxyqiakCtIknPhNHZnsjjxYTcYd9284g01rZajoJY2HhiBRu7hi6ETj/vtFxROgPzRjdZTfT98UkUG3xtyrVmfWBj+RDuSoNiB/hzITynsZ1QE3wNtCpXmK4aaytaZ9O85Iiv6kv+yyVYq+UacXq2frCS6EcUkMs8GAAY7XirQdORQ3CgjiCIvy7iGrlOS++lYRs+tMCdNDhpzJY14ieWE0sS5++dx8ZpYuxXA6wtIWIarGPHzKnC7ZzPwjhoV3x36LrJB0Ild8i7P4qjwX43hdhRZXc4y2Fopg8Vx8SkFGDVlGFPTarIfBKkyay4q5Zec60gHnDFywOGJMCJVQPN6I/sNE6elW5PcvbDdZ9chZPSNUwjOEhiNOD+fvFrGC1me6dkdXTdF3naNnF0IAD+nKnphpBecRmbwImiExcdQtQxyUmBN2fr2DBQumsQ==
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-data-opensearch
