apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: opensearch-admin-credentials
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgCDUquAj3MsGh6eWUB3sazr8r6h2zsoy7EXXQaM5NwGOd0QdoeLuXmKO7WDQPzRguWJ0Ep2Bk+CYSyVMO0ZrXSsKzyd2OnygWC56jYRlcVy8xo8iTScZ51gv5Tjccen82Svjw9xz2QtJ/nDC9sdFLnkKQxQPu4N1lBUtV3GiYsSRFKzdysoViGHyzXw+y3/dc2K9CABVbgdgvgX8+hPocrqU3TBw9CS1EUYYfOTgOvyhPxc3nP8vm/kEwh96/xTOgklm0JtEg2xxQ7uCzdIfkpccQIbw4eK/AyShl80tEImXetWyFMmtGWrddD1TCgD6IB6ofDEUvahy+O0PVya1ozLmzwAICer73NCLkcidvt39o3t1IP+UseTEUoH1XcxZQxfchAPI6R1nbtc/RGBxjGRjN8d9ohI43R2if7I1Kbwddgvf23awq/xm7QQBlsyajHOoaGcxZKri1oTvNwSi0BpbIqewwSrgHTxn+WWI5g5AP1X5eQH04Kt4ATB/Yecgw53pyOGKWkS/YycwS1mx3q9A5mxmSvL41Dy2EXBtdhkPaLdZt/AsK2F3TjdJv/916cP9D8h3LD8stuAZ8o+uv/qt/JTn5DgYIlsFxLgPIt52mN2CLINy16dmWDPjD4FZdCpKssLJuTkA7FDkBpwzvPyV21f7l/QHbL1331Hog/l1N+pQnTl4KeD08l6jKZ/iUU0IKbknItZ/RACFJdreB1nQDSWiJ8R6Jtt1f+u2A1+0g==
  template:
    metadata:
      name: opensearch-admin-credentials
      namespace: zylos-data-opensearch
