# values-local.yaml

# Activate the application-local.properties
springProfile: local
environment: local

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: false

extraEnv:
  ZYLOS_ISSUER_URI: "http://auth.zylos.local/realms/zylos"

  ZYLOS_TRUSTED_PROXIES: "10\\..*"
