apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: valkey-auth-secret
  namespace: zylos-data-valkey
spec:
  encryptedData:
    password: AgBgHufC7ZYONtzelLSPPxsGDoTjX+p4TZgfFalfhknqUUExbKmOri+xvhXYidLbv4Kpr/TNpEgx5WhqO3ELRm4cE0wS/406WzkDAOxuZKk7Yq3NxccGp2tz97e20pE0DPWLsTssqqPeke28IZtXe1EuZsNeggkf8DubXOSIL+jA6SHKhqdn0lU5C90JDGm6kJndYlRc6WfJ230s57Un3qcp1m+TtjW3iXf4SuS8cESxUYJ0ZI+AOJE2ng5TCYJV+LX2aBeZBCFbGi5JeGWY+hy5gNBbDpV5eBR1f6RRJNMAgackk+1lRR+GEwEL7xi43a6PUkfzVCZr+0ifZZMWJHqbclgAQNbw8Scn/XtcoLICjCPIMk0HzftnFbQhisFQwFCHNB0JMSXKZaaQbUsElD5cIwe8w1wd9HqpbcVoQKXPKrDRqpjziLF57jsnz1lO87yh65vnTuLZI5Z3OJlqp2H1ddXZoICaZCzys71HoVDj/ioiIaWfh8MxsFqUh8dZ5ect/g3gKS24rDnugslfDcJNJpbGIRi1EsPUY5VOTg5aH9QyhO+C84nh7kUCp+U5Ya/3sD7OOysuspD/txQ2Jmy20SsS65ETRImaCV9ypercJ241l2jk/H6wS6OX6eyfV3+ujKWp5HcpPUxcgyEWOISttWbwmTKYqpXoyG+h33Z58jqWZ6ZBVi7Gj3ZK4QP0sijQBG6pAdhmvCkz2yokmz3A7SKRGkIasaGSbBoL1KtKxVG38Gn+eYflqHY205AvvBk=
  template:
    metadata:
      name: valkey-auth-secret
      namespace: zylos-data-valkey
