apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- catalog-reconciliation-full-corn-job.yaml
- catalog-reconciliation-incremental-corn-job.yaml
images:
- name: ghcr.io/zylos-platform/zylos-toolbox
  newName: ghcr.io/zylos-platform/zylos-toolbox
  newTag: 349e30a977ff919aec9434f070974b3e5cc41b6f
