# values-dev.yaml

pilot:
  replicaCount: 2
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2Gi

  autoscaleEnabled: true
  autoscaleMin: 2
  autoscaleMax: 5
