apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-netpol
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: service-mesh
    zylos.app/environment: dev
spec:
  project: platform
  source:
    repoURL: https://github.com/zylos-platform/zylos-infra-gitops.git
    targetRevision: main
    path: components/istio-netpol/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
