apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: zylos-keycloak-postgres-cnp
  namespace: zylos-identity
spec:
  endpointSelector:
    matchLabels:
      cnpg.io/cluster: keycloak-postgres
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: keycloak
            app.kubernetes.io/component: server
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            cnpg.io/cluster: keycloak-postgres
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP

    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": cnpg-system
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
            - port: "8000"
              protocol: TCP

    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: keycloak-postgres
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP

    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
