apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: zylos-identity
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: identity-server
spec:
  instances: 3

  ingress:
    enabled: false

  networkPolicy:
    enabled: false

  image: ghcr.io/zylos-platform/keycloak:26.6.1-zylos-act-0.1.0
  startOptimized: true

  db:
    vendor: postgres
    host: keycloak-postgres-rw
    port: 5432
    database: keycloak
    usernameSecret:
      name: keycloak-db-credentials
      key: username
    passwordSecret:
      name: keycloak-db-credentials
      key: password

  http:
    httpEnabled: true
    httpPort: 8080

  hostname:
    hostname: https://auth.zylos.app
    strict: true

  unsupported:
    podTemplate:
      spec:
        serviceAccountName: keycloak

  proxy:
    headers: xforwarded

  bootstrapAdmin:
    user:
      secret: keycloak-admin-credentials

  resources:
    requests:
      cpu: "2"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
