apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-cli-job.yaml
  - ingress.yaml
  - keycloak.yaml
  - postgres-cnpg.yaml
  - realm-config-configmap.yaml
  - realm-import.yaml
