apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-config-cli-reconciler
  namespace: zylos-identity
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: reconciliation
automountServiceAccountToken: false
