extends: default

rules:
  line-length:
    max: 200
    level: warning
  indentation:
    spaces: 2
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: [ "true", "false", "yes", "no" ]
  document-start: disable

ignore: |
  **/kustomization.yaml
  **/*-secret.yaml
