# ---------------------------------------------------------
# THE MESH & SECURITY (Highly Privileged)
# ---------------------------------------------------------
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    app.kubernetes.io/part-of: zylos-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    pod-security.kubernetes.io/enforce: privileged
    app.kubernetes.io/part-of: zylos-platform

# ---------------------------------------------------------
# PLATFORM CONTROL PLANE (Operators & Tooling)
# ---------------------------------------------------------
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-operators
  labels:
    pod-security.kubernetes.io/enforce: baseline
    app.kubernetes.io/part-of: zylos-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    pod-security.kubernetes.io/enforce: baseline
    app.kubernetes.io/part-of: zylos-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: opa
  labels:
    pod-security.kubernetes.io/enforce: baseline
    app.kubernetes.io/part-of: zylos-platform
    zylos.app/mesh-eligible: true

# ---------------------------------------------------------
# PLATFORM DATA PLANE (Identity & Observability)
# ---------------------------------------------------------
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    pod-security.kubernetes.io/enforce: baseline
    app.kubernetes.io/part-of: zylos-platform
    zylos.app/mesh-eligible: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    pod-security.kubernetes.io/enforce: privileged
    app.kubernetes.io/part-of: zylos-platform
    zylos.app/mesh-eligible: true

# ---------------------------------------------------------
# APPLICATION DATA PLANE (Stateful Data Services)
# ---------------------------------------------------------
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    pod-security.kubernetes.io/enforce: baseline
    app.kubernetes.io/part-of: zylos-platform
    zylos.app/mesh-eligible: true

# ---------------------------------------------------------
# APPLICATION TIER (Stateless Microservices)
# ---------------------------------------------------------
---
apiVersion: v1
kind: Namespace
metadata:
  name: zylos-services
  labels:
    pod-security.kubernetes.io/enforce: restricted
    app.kubernetes.io/part-of: zylos-platform
    zylos.app/mesh-eligible: true
