# values.yaml

fullnameOverride: "zylos-service-cart"

image:
  repository: ghcr.io/zylos-platform/zylos-service-cart
  tag: "20260801-554cbe6"

serviceAccount:
  create: true
  name: cart-api

networkPolicy:
  ingress:
    extra:
      - from:
          - namespaceSelector:
              matchLabels:
                zylos.app/namespace-tier: edge
            podSelector:
              matchLabels:
                gateway.networking.k8s.io/gateway-name: zylos-edge-gateway
        ports:
          - protocol: TCP
            port: 8080

      - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: zylos-service-cart
                app.kubernetes.io/component: reaper
        ports:
          - protocol: TCP
            port: 9000
  egress:
    toIdentity: true
    toOpa: true
    extra:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: zylos-data-dynamodb
        ports:
          - protocol: TCP
            port: 8000

      - to:
          - podSelector:
              matchLabels:
                app.kubernetes.io/instance: cart-valkey
        ports:
          - protocol: TCP
            port: 6379

      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: zylos-infra-kafka
        ports:
          - protocol: TCP
            port: 9092
          - protocol: TCP
            port: 9093
          - protocol: TCP
            port: 8081

authorizationPolicy:
  enabled: true
  allowedPorts: [8080, 9000]
  allowedCallers:
    - namespace: zylos-infra-gateway
      serviceAccount: zylos-edge-gateway
    - namespace: zylos-cart
      serviceAccount: zylos-service-cart-reaper

httpRoute:
  enabled: true
  paths:
    - value: /api/v1/cart
      type: PathPrefix

extraEnv:
  ZYLOS_JWK_SET_URI: "http://keycloak-service.zylos-identity.svc.cluster.local:8080/realms/zylos/protocol/openid-connect/certs"
  ZYLOS_SECURITY_OPA_ENDPOINT: "http://opa.opa.svc.cluster.local:8181"

  ZYLOS_CART_VALKEY_HOST: "cart-valkey"
  ZYLOS_CART_VALKEY_PORT: "6379"
  ZYLOS_CART_VALKEY_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: cart-valkey-secret
        key: password

  ZYLOS_CART_KAFKA_BOOTSTRAP: "zylos-kafka-kafka-bootstrap.zylos-infra-kafka.svc.cluster.local:9092"

  ZYLOS_CART_SCHEMA_REGISTRY_URL: "http://schema-registry.zylos-infra-kafka.svc.cluster.local:8081"
  ZYLOS_CART_AUTO_REGISTER_SCHEMAS: "true"

  ZYLOS_CART_DYNAMODB_ENDPOINT: "http://dynamodb-local.zylos-data-dynamodb.svc.cluster.local:8000"
  ZYLOS_CART_AWS_REGION: "us-east-1"

  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/traces"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics"

  ZYLOS_SERVICE_VERSION: "0.1.0"
