# values-dev.yaml

springProfile: dev
environment: dev

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

pdb:
  enabled: false

autoscaling:
  enabled: false

extraEnv:
  ZYLOS_ISSUER_URI: "https://auth.dev.zylos.app/realms/zylos"
