apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - netpol-grafana.yaml
  - netpol-loki.yaml
  - netpol-otel-collector.yaml
  - netpol-prometheus.yaml
  - netpol-tempo.yaml
