apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-opensearch-bootstrap
  namespace: zylos-data-opensearch
  labels:
    app.kubernetes.io/name: catalog-opensearch
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: bootstrap
automountServiceAccountToken: false
