apiVersion: v1
kind: ServiceAccount
metadata:
  name: zylos-cart-table-bootstrap
  namespace: zylos-data-dynamodb
  labels:
    app.kubernetes.io/name: dynamodb-local
    app.kubernetes.io/component: bootstrap-job
    app.kubernetes.io/part-of: zylos-platform
automountServiceAccountToken: false
