apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-mongodb-app-user
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgDF40QxAtcixezIM6rj5jGQEreDTFpKkPpxZgg1J2FQFIU9Y6LO0gTZx7+ZMYIA3UmF4IM6Rp9Y0iOlq47OFyG8wa8TCBDQWNlcEMYLkeLeS4scJ8mDRfQG5mh4wbNPyjfEPxjVJHSzVj3yg74rQ5toExvam200ClIhqkztcgXpX2fAv+YIp4KMhZi/bTIR5TTYe3GqXs2mz1GThFc1y7Kt2FLGRL58r/bU9jS4XO58O0RY7Q3CZRau+cNgIQkQc8ov9DSSkE+KMOxHHGYGtRyCOYKBx+MHqjqqVo3xJJ/o9OvqN+I/neb4jPXS0BXlafnyYkV0Z0lfqRkaCvNV703O4lG0oxQtF0ra70HyAjaw8aGpA1zlrc9BscnwLO0GcMed8iyiUSfv3oBGXKQWbM8HRJ39cEVZnd70utE9gbm5WRLqcLXIMf5t4OPgdfMi4h9vSMPHvIHog47t4LOrJEUxNjB7Md0UpG/k8TvPNfPQ3aA0UtoCrbGHIFDON0VbcuF1O9WFTlN8qfn1E8FOVgcCN9IMdCLqmqrczROLxu0cvem4ocz6m/o4tgBdkGZftF/P1ChV6OZ8pQq+BvfMS52UNWN6QojGiUT8Aqi+FwiHLKace0kOpXnbZpm6HlY+3UNYaY3iZHlErCE/rXJUDViaRtZOm+UAwXEVQkZqWifKZQKqEw86bbQf9nN6LU3ISgOtwnfhj4SX2a9h2WUzz5Jdh29D3IkNOreXEWOqAeWJXgTwvm0Ww0LaosPGF6PSZ0Y=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-data-mongodb
