apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-app-user
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgAZRhLHWKhIlWWsLedPZl/EdCrhsxlyTR7Vei5L50zTnYssL62tCGneGm7gZSV72KGJHuKnSpojmE/oQ98jX8UIEYzHzTc9hHEw3HhCMTWtru89HILPxLLtax5cENsK3ckpxuwucMtsCK4TS/W/ujP1LWW70JKkCk27Rz29xDJbSDbZvNgmsxWGSgXl2Rh1k7mlZ1N59bFGHh+sF0L3ajB70pjLV3XFQaNNBr9lZz8PTaUyem2Oiu6bXdvMF4bu7k0oDNoesFCFunZMOP3K33iUY9l2qX9i9L/3wfbl0gZk/nF4XdahgvF0WWvcMRT5T34eRtyhHQkQ/1chTNXkxqEPpn8ta7XZBpRmdsC2zf8B8bElHaLlb2QpdE+9MB4cFl8VgBLj6f8afLGyZfmm9sidgomP2F/WWMyBPsNtZE6tJllo2c/sbyTdcV+1REY4AOiHm5OnEbugB6MdLpkoAn6aURgrC6niLVrNXgJrHz9U4KOv6ur9rEUXJ8NjhW4jsYNh+X+tTrYtxkqYxoex7mF2iBjRR21bRYsALa630/AfT7/ktfBIsvPEEg88yAEbScQfQPjXXw6EVUUQ5CRpw0A0gfMQFkdaytL5FYC4i2ZK3Dc8HTvQIhfSTInTKbhRWji5IgIBewRefOlMswNzVQTJiWHV2beCduxlCXx8vgkinw+PcOL5bdpZDkcfXCH4o9ijEbXkeEyOa3BP8RJ12EMNHDqL1e+dFpYxIqhb1bgBmNDMfGqYEJqgqeP8pZAs/DM=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-data-mongodb
