apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-app-user
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgAV37paqTV22QnqX1cJ1WFjPd0HPLfx7vzS4biLXUKwxC/SxLNVlAP1ZACR6FELnQjaloJMsMtgTpwgOBIFEz9ZahLCOxMvklOuE3BRp7qc6OHQ36/xmJ+W1Jvrubdu5aZ2IAlZ8fJKGde6uYU/o8zZjm+07AF46ld9fRPh3xYwbEdNNOieHHis4kImEGWScekjdGjuKkuclZd0ma8sL8rbZovPf258SnVkDRwHRfdXujhostdr/aLidZfCoBb6QbZuwpGfeDlXkmuPjc+/96C8rzwyE5IZ0EFpTHHsdpZl4X288/MUMRZdD+dDF1PmQYi1ZcGrKaCdORx7gY26OUxx8M05e3lWJwt3Ga5FxfE+JoGtjEaC7Xxtywgh88V56YpT8mMFsbSkpZ+LOD2Nw4BMzpxA6zXa6OPVnb5R2Go+5F7GABTDu70dP+zI7BB0MkW95tNDUMOO89DctEmuxxW499ggHfwTEeJeyTZx3NefNqC9aZVyIVvSQ/d3wmnq5i82Sg8Csz9XHQpHpA1p8PnKcxmWFGCL4/aiHMyyleaQKuDV3uWZNK+0b9cUgS2EIn3C2HLVFt/dzCK6XHaF7T4Cd4jp0Q/Ma+Mpp+TkF+N3+fTbENP+RzcpD2gB97LweznwuoIFUKunEx2Al9Z6VLY7jHE69Rfji1caCbk7Ci9VY1Vr5yuejHDcUp08YytnXK1MK/Yc3UIWOZsbcuoT/D1wAbpPN0hHXCNBx+lWJM5RTVbjb2EfPF4QXCI82VkRf9U=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-data-mongodb
