apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-debezium
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgBBAeYS5J1QbvdS+bj06kjwJj5FgUg30rY736qnFmKLyHbXkLCPi5JW675E6bN0QB6UFxTnWYqxTMq3X/nHdsTuR+2snRbAbDDn5XNeAHoLnGpp3P3EKem1HIWgVdhCcGoqAJTGAGoblkI5nt4dK4+2CWqF3Z3c/bZZmJPPgjxdpbWADlnqamRePrXIJKi0WpQonPKgPpCwasXH6dqjq2LC1hr+DhyucTDNEy5tvm6oKTIoNElQYoJBJfy7skSeomGCLX3FUMfA9GVlWeT6PJvASnl2sXTCm7NpI2+qgzVjMpopRjcJC4O5e8jeEHMjQZUE8T6uJ+ml4mq+UVBZC+OGPeNy1JH1vHQ1zTdT/Pa+K+PC3nY0SYUjW4mwJnIiGaJnlnznDw51JaqmnxMpCZSoXbR7E9AcO8XzoQLvecfFppHT3TygIqX2v+wmOjZo1zQXbhKAS7HQnEGwjp/JGhwd3FLTpTcMEiv1GwhGhbIfhjPm23qHvLXrVe9AMF8BZeX3RNX3sybT/1vBOF8ePI4tTy5W0jzRUK8zhvvkW1GwOq+mOO9ShYcumQ/dkiNCutgraSU3VzwPxYzoSbPW6MtZduncfArhFiwKmMFn2X9FvZJOjWZOcf8i9t/AGRNDupcpEE6ngAmnVFKxH5tODDt2BS+1HdP/u3DF/C2YZrIAVM/gEivvkBYhm0xh1yKoKK95bo2OBi81d+PFYMUJkhL1Tzh5bJAdjeZqS6KVO09nFDt4SJSmhwssc4+XkjuV1Oc=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-data-mongodb
