apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-debezium
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgCv9mi8SAPfxJIxuHGIre6iPfjEYhRLnEzq+5EARbnZMjeQCgCQ7Q1F1bQr0oi8YAAPd+06ZGhdNmE8rDbBi7DO4POybie/jQOkcCfy5IZwLl7Y5+1X5zq//MJ5uQqz6/VPHoCnf5V8ic/kxFzYNb/saIjLak3W2Q8oi9YWaLDNkDkik2MLAoE78X00ta6eqpChr26snXcquDsrZruGTyek69ecS/1/EiMUpz4P3QKs72Rs3bEiHonf38F303JXkRp33rxpdvVyqmDnNCxR+iyY2vBLYM5dnotWUex7BnxHTT0aeoorfQcv9ns/b/6IdY1EhOTsbuRWawnEAsRT9+WUoPEmEufDWnsuHS6+b6l/RZqtMECRnl28ssX34p3HFns4AgCdAQ//XYaqDSraU1S5jQng95JlFrUwJ6PElf+GMwoCJO5TcXs3MNcbpr3IBRwanYjREawI1NG4dHpk+8U+oXzA1Zf+bxws2WSGgXS5XSc6+swOrjxJ3J4mcCPq0qxQtDGh0++2Vo4abRh1kidIwfjUwrCecOHPwfMIMvf2pFuns9WIc5HC98eQXC4JHgF8agarRwWpwcCW1JAiQj3H45Vv0My3T0zVjtw6vxtP1JxVOhCwEggv2gmUmjf6/bCYHGJfnUvovBugFDZ/wD8GDNRnhDYmKwASMWxBB1H4/d6IsFT/M8K2KQuq1oq16M4rT0iRBI8qr4anuoKng4YLXozUMrmh34ZbJ6wICbcOz7fuOKTjxjUzkpU/GEsnWXI=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-data-mongodb
