apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-mongodb-debezium
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgAxbjcMfaIcEJb6LUNgLoQEy+TW1ezgst324NQK/SxbwAs/IfFAdAGXoqaVqB3J+pqXse0JFZnztWJwNLBnj7c6fU1QqH62trdQT/P97vSt1t5u3T1j8jgnFWiQvKwSTDyxKr4Ml2vXLA0ZWdBOb3DGBG2oy2j7gND2qCE9vyX0QEtSB7VGx/sS40tEs108YoFxakIB6iGYnyiF/zUib/TZLRyQWzLcY13Cn4TjS0znbUC5tG62nNjJg9E3hkst9iWUgvgbJyIELtiCK0m7/TTCaHtsMBvJwoY9ZAM+1JY25EZwN1+ShdJXBC4DCZsGcRS/+grw3R6lAWfKIPXq2MV/CjMpTDknGmP6nXokm8oREFOmckcFY+OyB++WCRJ6zoelztKCXZF//P2U5TPXA1UMNvxtfL8bWhYxzg0bHeqIQxcWz8qrrErypEHn/TchytZ/NU9hPfmRM+UMh+mX6c3VTrlx72QCIxANFB4JEAQhrNGAstZEXWPfmuTjxboHkSxcRud70kIQYV4hN1nO0P+bvmVh3iPtgANclQFuMfUNOy9MxktOa9eRVGL2LX0K7g38PUwSmBKCAHKPy6TvoqcdkYmRI1AefbQAoJc6ER446rKg4uqrJwImnHbQzBufWjhwHsHH5nzp8gSIuwGE8MbV40qzoaURoJLLqmrE4uJnP8U8M9G0ZGW62peCFckgAnYj1PQQ466OzPmV10r4fitN7JDEGAQZvTquvokGaERIMNznk4qca6xmTzXArrtPSyE=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-data-mongodb
