# values.yaml

auth:
  enabled: true
  usersExistingSecret: valkey-auth-secret
  aclUsers:
    default:
      permissions: "~* &* +@all" # Grants full admin rights to the default user
      passwordKey: password

valkeyConfig: |-
  maxmemory-policy allkeys-lru

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: zylos-data-valkey
