# values-local.yaml

dataStorage:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 320Mi

valkeyConfig: |-
  maxmemory 256mb

metrics:
  enabled: false
