# values.yaml

auth:
  enabled: true
  aclUsers:
    default:
      permissions: "~* &* +@all"
      passwordKey: valkey-password

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 320Mi

valkeyConfig: |-
  maxmemory 256mb
  maxmemory-policy allkeys-lru
