# helm-values/opensearch/values-dev.yaml

singleNode: false
replicas: 3

persistence:
  enabled: true
  size: 30Gi

resources:
  requests:
    cpu: 500m
    memory: 2Gi
  limits:
    cpu: 2
    memory: 3Gi

opensearchJavaOpts: "-Xms1g -Xmx1g"

antiAffinity: "soft"
