# values-local.yaml

singleNode: true
replicas: 1

persistence:
  enabled: true
  enableStatefulSetAutoDelete: true
  size: 5Gi

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1536Mi

opensearchJavaOpts: "-Xms512m -Xmx512m"

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-credentials
        key: password
  - name: plugins.security.ssl.http.enabled
    value: "false"
  - name: plugins.security.allow_default_init_securityindex
    value: "true"
