apiVersion: v1
kind: ServiceAccount
metadata:
  name: zylos-service-catalog-reconciler
  namespace: zylos-catalog
  labels:
    app.kubernetes.io/name: zylos-service-catalog
    app.kubernetes.io/component: reconciliation
automountServiceAccountToken: false
