---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-mongodb-app-user
  namespace: data
spec:
  encryptedData:
    password: AgBGPCapGpColuyXRDhCHNES2StPXvkbPBvF0gsef8jq14ywWdqrN9XOWcALORnyEVM2qTJ3K5VIKWMefAO/1YRATKFbx3lVby06W+WbXCrcYrQLHGa5OAtlx8yetQsXtYG3SIQXW6jcy7DopPNQbjb04PXzjE//Cc+wyE5d0geyvXXsqCO8JjA5Ng4WnRmxK07qlpE+zxsqikSOpleBAwkw47I4I6x2y2ppaBHrTyR5X6Bo88ZNRWoZ5OAPVVQiR1iGphdDffQNGJJT0DNnSxNOYXgv2vcIjKYHj7j6yuXih1WsoaNa2DbW8dHx6oTRgY4likTFsPwLqDPHt7d6npCmmyl/yt1OORdL7tV5yWIg70rCtXMVKcKWylIdPxm4RW7qomSXP/Kv/sySanFiZzIwNsnijcrmdIfXTKi5tDHdj3FlaXHZ+psY90gpkfOsv3G82WmhQmdq/PyHPKvV1SNWvu1nFKTY/FUVlKaxszx0/j/+D+AXom6UTMOr5zHN7KbgJfOgcU7YvgUUQrm1GWZzmmwwBKKjz4E4zfjPt42vrdaOAnop4fxUkKE8lOIuVm7oU5AeCykjiH8e96Kckthmu5FGiHlj9vFv8ZwM1A8+7J3edH50FOIczKLfXxutWq41fBb+5OjOqb+BX8N5stukVGLA6K6V2bx+KeUNP0p6hUUJS8kzHIH76o7iPgykrKjU9sjW3OzMRixUyH46wufnScaz/mBOf4yohsKptyHvvA==
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: data
