apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zylos-edge-gateway-netpol
  namespace: zylos-infra-gateway
spec:
  podSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: zylos-edge-gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 15012
        - protocol: TCP
          port: 15010

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: zylos-identity
      ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 443

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: opentelemetry-collector
      ports:
        - protocol: TCP
          port: 4317
        - protocol: TCP
          port: 4318

    - to:
        - namespaceSelector:
            matchLabels:
              zylos.app/namespace-tier: tenant
