---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-mongodb-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgAhveiszhJEaVqV7m6tBhOa9pGlRz3GZpmoxclxpocf1oMLkUs4Crm8NJDfUXN0CntmABhqXpBwNT4q3z1W7gcPNmP7PYrdPqHQXRhhXtb0VxRoi82fzV8UNhwPSoV1hAGluxMpMjf0TbAH6il8rCkpMv4GMAAt3vC3tMs5UpODAvhqLDUJ1/jUmiGYgj6SL9rZFnXJZurlDdH5+oFGrJBcGxW6m5hvcAQD3lf1t3Au/boaTlCMJT6IAxp2I5+nTVofVMcIAYr/xa5Z1XHpAaXFfbdvTAs80F02jrSs6wAJxjjXYsdGkzZq951BSPjKO/Wa+GgU1x1dHXu4Y60p3do2fRTTkgca6CvEFpRiSjbCKYDQHwH46Z0/I7IfPf8npaZMVidhtJmzChNeEBeLlhm7i2nV2n6zq/IaTAujNMu81f2rQmE+d6BQDFI2cRX5bsFWJF/K+71RtH5moUo3EE8N0TRbfePojLUhHg+dE7QFRls+EdknvFvZOesuXCZERy2QkLI3cjhWIq8S3s+4QyCMN+jyEW1zpC7VWxHnyJxSOesjuUN4zRnc7gPZazkc/aoZvy8W+QO1hp0E1nO0qCXHF4+9sXn/4kpLxuDOlAnIQty72vOdQOag4USCLXozh8byqysy2nJqiOmQHRmHjNfzWb4XoBK42Ok+C5FmIYz79E7+ebZv8gRwhELkiSLJEY87XeQhWc2bxJJet3H6iU4ut2W1Y2BZcG2Sj9KQtwbFYw==
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-services
