apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: authorization
spec:
  project: platform
  source:
    repoURL: https://github.com/zylos-platform/zylos-infra-gitops.git
    targetRevision: main
    path: components/platform/opa/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: opa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
