apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: percona-mongodb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: operator
    zylos.app/environment: local
spec:
  project: platform
  sources:
    - repoURL: https://percona.github.io/percona-helm-charts
      chart: psmdb-operator
      targetRevision: 1.22.0
      helm:
        releaseName: psmdb-operator
        valueFiles:
          - $values/helm-values/psmdb-operator/values-local.yaml

    - repoURL: https://github.com/zylos-platform/zylos-infra-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: zylos-data-mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
