apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zylos-netpol-ztunnel
  namespace: istio-system
spec:
  podSelector:
    matchLabels:
      app: ztunnel
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # HBONE from in-mesh workloads
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 15008
    # Metrics from Prometheus
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: opentelemetry-collector
      ports:
        - protocol: TCP
          port: 15020
    # Health from Kubelet
    - ports:
        - protocol: TCP
          port: 15021
  egress:
    # Ztunnel MUST have unrestricted egress to forward
    # application traffic to any out-of-mesh or external internet.
    - {}
