apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zylos-netpol-istiod
  namespace: istio-system
spec:
  podSelector:
    matchLabels:
      app: istiod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # xDS/mTLS from ztunnel/waypoints
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 15012
        - protocol: TCP
          port: 15010
    # Webhook from Kube-API
    - ports:
        - protocol: TCP
          port: 15017
    # Health checks from Kubelet
    - ports:
        - protocol: TCP
          port: 8080
    # Metrics from Observability
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 15014
  egress:
    # Communication with Kube-API
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Traces to OTel
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 4317
    # DNS Resolution
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
