apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-app-user
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgBC2n86uIlsskqMyVOvflUOXqtnMjj3d2+OaJXfYCRLCJvxMAAG7JB2M3Zm+aoZqxBoOomlhJfEA7p4iJLOml1FOt5zZMsNeDD4WezpC8dkfvSEYrfT+obwjjzaOBpkWHVMfCKV+50fFMFjU/yS2aPgtvHiamGcBoWUw2oin/Kdvd79wk5UYJkl6UHaYy8SnRkQT5dSfoN55ECD0NpxaPsHWGjGAITeNmTo1IbZfGiRKP1iLM6LxnQMSqSJyJ8h9YA/XqPhZgAH4y7EXC2cr7w5GJl2XhQEqYSAmC+Tm3cU0aw4A/zuOElnCNRfI2lRCFlpkJR+NO2K5Z65Wmi7jFWUH/c+suM9NdGY/asyz+nrmyDbL8YW4mr1i8MB5OG69p6abXKTitn4RxxU7Ad9KI1j5scGGjPZGLpCx6pBNey1yGceO+HOIUMgp08W1lODG8mKaWcI0j5GvjwPL+OdB5lJ04FXCHxTibFpQ2a8FY29+ypSkX/qnzMxJPRSxQEGe0WX1g3GY7fABfCVvcV4MQSIFwZlSBb/xSGq3CWy8SscK0ev+lID3wksCYw0h/OO22889JOKejfEtqxuYW1pMUiyt41eg1uWwXvE185UzjzhTfD0nPtmxUMINVZxuT8Uw9r3WORu5ctzbV8V6961gAobQD+RUZsJjFBGAB6rZh5oLytLYE4yxOZlrIHwuz7Ync7UopKJOqO0AfMNvnJwrxgbSW88zULHYAh9OLttmCl/dJmTb+T2bjCXMMgNR2nWOiY=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-data-mongodb
