apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-debezium
  namespace: zylos-data-mongodb
spec:
  encryptedData:
    password: AgAcl1uwyu5xjrqZobOSoOF89xY4iaWZrdK9InX1CMUYGKtBq+iFuGOnjzkfR4lVpjpYwGneRP+qZGfn9EnWUJcJoTmIM1gX/ROerSgI2MwfdVuAqDLMuNxF/9uULbhCuv3PsCH7rMfSR6u8rfP2NVn3yJFcHP+0+3QVZGLRBg5FlbWwgE/HqdRglJ73wLhtUKsYCxRUH0Q47mN28bIyyW/tIBniIRq9Lbp0sCDLnmmyunnipn8Rq3B7l0WWz/DRD9lQyWBxoRsLOIdzrl/3XyyUHUuxAiuVcqQkgKhkT34bzKOZiQjRe0MQU6RSk/Sd8RN3JXrZl8stlZglaSdQa2GHyo0k6mek7fr3D+8v4/aOgcACnt3PY+i+TAynCjWmuxXHejQ30FWINXSu+PXaHH7nrZyx2lX60EPYKxC0IFkL8ApVw64OL36UyObf3IFYdGwe7qEcuiLxc64M6dhF1j++2whzz6ICBMTGWRosCf8BdGNdkBMOm1JtLTPI/MktcWLh5CZ8km5/05fRrT+cS2xhWsho6Vqcz3S3RREUMk/Qy6Adnfx/Wk1og5ldimp60VQFDU587PoZZ/avn/Rx6ukiAp+dSwQPdW/z0GtoOyL+/l0PTxTsQFVVbOb7NT9OQs8dNwoiCGquJximdq5aOpJ6THiSmfCn9ObP5fos94q2UullyM3jzynYZGOTJkeaM05AImlACOMt/HpCjR2nBs5R4zXfqlX22rekq7m46/RmynLRPqPKiIekm7xUxkKLD6Q=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-data-mongodb
