apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: percona-server-mongodb
  namespace: zylos-data-mongodb
spec:
  unsafeFlags:
    replsetSize: false
    tls: false
  tls:
    mode: requireTLS
  replsets:
    - name: rs0
      size: 2
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2
          memory: 2Gi
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 20Gi
      expose:
        enabled: false
