apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema-registry
  namespace: zylos-infra-kafka
  labels:
    app.kubernetes.io/name: schema-registry
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: registry
automountServiceAccountToken: false
