apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-default-deny.yaml
  - 01-allow-dns.yaml
  - 02-allow-intra-namespace.yaml
  - 03-allow-node-probes.yaml
  - 10-prometheus.yaml
  - 20-otel-collector.yaml
  - 30-grafana.yaml
