apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-debezium
  namespace: zylos-infra-kafka
spec:
  encryptedData:
    password: AgCWpn43QVGasquBneiCCV2+5M+YtyyYqh0wxc0J9Y91pAhpHKRgKI8n1tqjgOSYJHAAKXkNKCdYRydU/Co4EMeWmw0bYuHHgNCuDZy3SEb+VJaMvb/EpcbyyXRQO9NzNCm7O1bbKXkYYckW0lmXjz35WuDX3WUAw0il3iq9BhQSUZBiO3AV1BWSiI7CDo+l0xMwtuweUNIcffSgQitrEQuKabhWEnv5CEsibNRBH+0aRAEmruJ//+nvexo/7Qr3NmNdUTcmaVZwVXvLg1H3nD8LogJshGNNaXsBYtQqWShvFFNkfQv+JYdGCvTcuLqCeYpV9SINb/t4uu7d97Dsh733dAHR7dj1CoA/QXfk1Lraw5T3M3AjLWt1woZmKfLwvpPcPM7Uc1C8fWJusoj2ifABdqmM7OOKbSIl/m+H2Zn+EnjpATS481gtPUKnwMR56TQnQAKkvgORHa5IfVoof2u3Yr3e21PvS0ijZscp3Rrn5A6t8zzTC/gsBGPUu/HnQnBytiTKXqj33WWZvcCxcKAP4HJSZ8hp1AzfXiRyTjKV+nKgCuSWBbrc07Shp7t2SBWRqeRQG4yz8payqbZLP5oDlAmtS24p7+Sx2g6sAJ1k6ZBtnSZdxQxf3kIUx/cXKI9NoRmF6HOr5iFfWSLP/2o5kTlMb8DpNqyYZJDSWH1jpIawZ3HkT3F3gFWbq8KB34qYfY059mYtexhNXUZOdHV7GUBZ5LU08noOacl/Ss3y3pPk6GB48Eu1O9eRpFijl6A=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-infra-kafka
