apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: zylos-kafka-connect
  namespace: zylos-data-kafka
spec:
  replicas: 2
  config:
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
