apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - catalog-cdc-secret.yaml

patches:
  - target:
      group: kafka.strimzi.io
      version: v1
      kind: KafkaConnect
      name: zylos-kafka-connect
    patch: |-
      apiVersion: kafka.strimzi.io/v1
      kind: KafkaConnect
      metadata:
        name: zylos-kafka-connect
      spec:
        replicas: 1
        config:
          config.storage.replication.factor: 1
          offset.storage.replication.factor: 1
          status.storage.replication.factor: 1
