apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: zylos-gateway-secret
  namespace: zylos-services
spec:
  encryptedData:
    gateway-secret: AgAHZ2ZPUj+ofw3C1B9g+/Bqfent1ho7V44nt37aE1KVHYnK17bWH6hTMGM1GZu1nwhbR6/waJ7uS8Dp8/2PLD+bOsFoiY2ecs2owvcwfyzZzyhYtmsFnUXQkrn5am8WhCOEPxDqLbc0hsaWkoYeFn80CzE1e68HXUj0Kl0RMWbvHrmAXxxYQHEZMvWieXA1dGpBpb2+71elFPWAz4VBhKOdi0QfqCTiTzdZyPvTcKH0fCh+r5UlmWDp+B5KOdd+ZrAMW32KHj9rOXjaqtUO+UOPUWYmilGltI2VxNYpGkB/NNzQZClvWwZBnSOSgS6+er88MqxDPz4VPHZuR+zsPNZ/xmBbnvJerQ9CgGkd9ZLxegwSFteS/D58m9TBzR/Hoj8J1Ubsw8IdH1614U/T648ZT7w8TH32n8Bpdf8a42bRyBHGKlN5hM6UGg/2iGH0F2sJYbvfsL+C3AtbJfWIBtfA32b11tHLBxE0KJpyJLHz2lH2gFfNgGxFN1BUDYgcQeDZwMEz5f45u0B4cMbIl3LV9zNPCzJuhpQ1KQ127fp8DSTGoyPFS5+in8E5qkoxuZv8FI9hBrBkIhEZ9JpC1KnXYj8k7RLwmVPSY1NlHqb9YlyCBEsr90FCWFpEeHp7ySo76xKztfcjbYMtOU9YcESjDUT015nmxkJJYGjnjvRdczwIOlTLTzzOo4xgrbbWcSykjZNgMxnEiaAZ4uRmTQ3pVpu7+9AIaw==
  template:
    metadata:
      name: zylos-gateway-secret
      namespace: zylos-services
