apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: zylos-gateway-secret
  namespace: zylos-services
spec:
  encryptedData:
    gateway-secret: AgAGP6NiBSZ2LY4RUhUp5gYvT2sszHhxEnI+C5Hp7Y4W9sDauAdv1/ZV6FrOkfTIq2DUGVVNIaThoRRCRQ9Phx4dggtftryuNEtYJK7XNp5o27jf+hS4WBSDc51o+HkMxF+2GN29lLBysElGMeearGST7Q/hA5E90ddBRJ9i7k/luq2skNgaZDwEyB05gOwBGf/nm3R+1/2+YUPw/M9tZF+xFa2IhJmP1N0TCqIsSQSs831KYcqOm1zaFofx9avpBezf7SsTzeByd2qqIIoNUAmxlOjBQ45uyEAIl6/n0eKjsuC4LaSwug7ZLI9ZEiee9FvKHiII9DVn2UlvohpPQylrevn1IGoAIlon4aH4XDgUmo6XWSMDkp0MlPljcwCmX7l++t7WTpX9CtyvkqptyW55Y2aG8bz9mpkTAIm0VKu/LFgJSwnTkD+MlnCkVowHaT42BvbFz1Y9rfahwYLYosuvC/crNxBDSn2F89EF4cytkvVXI+zaH6gxmGQlMycPBv/9IMwZ1E5utMyb1Orv+Z8Qgcc+UMA2aU9SBzGQ6YA3qDLArLYy7p+HUOHU3wydtCT875btxd1k2sk0f2YMsGL/+VjdTyZWycZ37bSbfWF7jaUZ6NdPP+7AvzOIo7E6l24NCOrZaZFUw06OBk5HAaAcMFvf2T1kP5CQ4mt4fhAVimLJaHuPdzcZGabtCZH0piBAZE3JTEOPtf7GIArDaCZru7L6TQkw4Q==
  template:
    metadata:
      name: zylos-gateway-secret
      namespace: zylos-services
