apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: zylos-gateway-secret
  namespace: zylos-services
spec:
  encryptedData:
    gateway-secret: AgANIQuk6lbLrJIFhy6t2/dixR5prglMAdOVgH09uErzYA+gRjh4yMZtQZs3oXarCaaLTVW0MY+Y6Zee0Qe9eZ+rZhSYdwHCZB00PrQzQ3F9x76NvAClo1FN9kI4W0jjSykZQKVY/VaZhUP2TEwt2IxqzfRnuh1xluYnIkVFyJRwAgxuRd+CPh6KqipOFCq0a0gzr7JIJBKrH5TskUKdycDYqR9KFgbQFLIGO/EsajviFYrN9oOAfXG9yKaa0A1pF4ztXpiRVdnYX3It+spsEo5hOogVT1VjVNZqjwnl/cBKZvV/mQaVBEjFIUX5fFQKZfDFcLfRbtGq19UvIHKNWqNvupkn5pCg9/crpzmWplx/s0licjy3tnlEDilbxhbgBdk9xHVxadFswunQMqkMhMp3nASsUkJbhgYCZiZs4mvfvcnKklpXmNto2Y5qw7taOZI12L6safROZWRxTfzo/UEpDBq5+hx/KUduROWr5nPXpl9hRv7xxnvOqq0mKdi7JPX4m/G2VsGAf+HQRFeklOZAW0tSxYKnK2kx6x3iJ2nQSxfpus3V5uG0URphuiZAVfbKQlIsbx8qKohficbn1p9wCftnH32oJBYNOB4T8d/EFcekWQ1qIgyMUcX16rCyYy3qD829paF1wSzhl6EsudFC2VGjkboySU6dOkJHe+E3wZEswTH8yUL6DRH2ANq2gTc41jSbP8Ot1MYBn7t39ExymIM1scTPVQ==
  template:
    metadata:
      name: zylos-gateway-secret
      namespace: zylos-services
