admissionController:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi

backgroundController:
  replicas: 1

cleanupController:
  replicas: 1

reportsController:
  replicas: 1
