admissionController:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  metering:
    config: grpc
    collector: "opentelemetry-collector.observability.svc.cluster.local:4317"

backgroundController:
  metering:
    config: grpc
    collector: "opentelemetry-collector.observability.svc.cluster.local:4317"

cleanupController:
  metering:
    config: grpc
    collector: "opentelemetry-collector.observability.svc.cluster.local:4317"

reportsController:
  metering:
    config: grpc
    collector: "opentelemetry-collector.observability.svc.cluster.local:4317"
