---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-connect-build-secret
  namespace: kafka
spec:
  encryptedData:
    .dockerconfigjson: AgBTlC2oEjUIWYUqmLwMF8ThZibT8CuggPPiNVcpLXiKRaXCKw6iB7813MR/dALO5pBv7ET3R3UxA5cKY9iUAwhLMAkkpYkBGz3AekD9Ip6TZBGdJr9AHqi34aPZT8jnTlGGvXYCBLVf0P/6RGkNuWtl/lDdJrcDVeOemkm5HLX3YY5Jv8dz2AbpuW/zHdnp0Pq9TdLxXq7IYx5ULrOkuFjy4BTU9cVp19EkdB2sGp4Y+tmK2BylaB9FLdHIsxwJYIGvsJkmbbF7njvSqOkswB5RKVxGOy9HYQa6J59dS/3SFqrAxbZoj37SNbjFxBriEubI22CRSTVM/JBrWUwR2WvIQGX0xFcYzUDqW4IRfuzxJVzNHZIfg2JkdfQYTn6hP5Y33E6fXCaVCS7bKhI+LzcgqNhJPY0efMvecftmfN2vZKl1VA60/2ufDhVz8gfBgluKjpwGdQ03O0UHYRh4lHiXZXaXozyBtBscRBIlwTCbXxcRksnIPiWqNwhzrekN8Xo/ohREw7Rj33DihCOmYPF4lcpNSFrE7i9/tJUSafo6sGworT4WxENjMNQ2lysR05UYnsQC1UE9dN+qNVQp5ff+V9DDgf2Y7w2F5wSgM8Qe38q6H+tynLkvbli9Fiz0oMMZko8udJHen/nZtwbePfycnmzjYnVhN1cJ6U/iO4o6/6TLuYjgPRLDkGpHOvyBvQKulMCrk4Hd61JxQVxODpncFJhCQ0Pv/WNJnEZKY0WdJXJuCfEy0oKjYGMlEkzX61Z9Pqs4qDvu5kGIJCkP333fbqTxvQK89AALUhO9wqIZoVXQH/zJRFaLxRlNMrsYZcEEPe832+mO9iwMykIN7n9cRZ19MIcAD9P2hfNBcFF9hDyGVCTBqXpj4ZfgTxCzyED4xGsAlkYDWlWWhGq6CXaiuVbcIJ+cOX4WbH5xYe1Jl0MLEKhodwlxKGH635/V72umh5ql4JUd
  template:
    metadata:
      name: kafka-connect-build-secret
      namespace: kafka
    type: kubernetes.io/dockerconfigjson
