---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-mongodb-debezium
  namespace: kafka
spec:
  encryptedData:
    password: AgAlWfDY0fwQWdDO8nEbg1YJNhyfIuorKVAwRGqSuq03cq5qOaaVRkBUucQQDy9k2luiax2u/Ej28H8W+qqp+Ia8cDHMt1RffyxSlx9SPvO0fNJkXt1eihmSYy/VWQRJhH8p+JMKqEnDv4B/PUHVwMsr2KmmjKrWg2LWHsgF9sQjjG2utAT4nD4OQ3wUmRCDs7/BvEobbxu0K6KyNX61hceLOXEm+aF+goJIcuCBCrdQamM5zAUkGNCFxPF5PsjLmuqDwS8zUHq1il+ymtR8og9OieL/L/tpxkg6Ebn4/EKkkKbONywJqKA9ft4y1c21uHwxkNj9EY9308ylRyI8++NQsbZQYFLPOFjy7MxkM7S8SMBmaUVXA38Xg11Ympcec81OMNJGo0GL40XTiPrceDxDGkkIzXye3yTHTg9vOjrVjfCoUtrFx+uNoPSEJwhLFyK+rmusd4/cRgMl8CrZg49o6pUEWemwESsFyR8Q31vK1nNfBxmFUdgyDvlsSXETQ+gcHxng5zjLZ5N0EnV7YOeoTtZhPxaqNQFqddmyh7nSgBeNX6MgmS/ou4lqa8tqKTuCrgb7hsdfyC2qLAcP+EVgACKhYID0hORTIqR6yrh9jLrUhzhy7sOk5N1YPmQR4iYe5dFoCkoi/CC2u9r5+HyGYoiFvhp0G/3d6imJa0MvGEXkvEsj9u35uOB8lBVfM+xCX1dO/5igqrmd0+wUx60b104grJxZTnVaM9xOx65PoA==
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: kafka
