---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-mongodb-debezium
  namespace: kafka
spec:
  encryptedData:
    password: AgC8IMlaZ0mKmtPI681m7HZLxpq8DepyhF2LGtc+BYO+4wdN6v7o8zTj/4xrlZ8HpYmDKuk7sy+aQ0MxBPl0QngKLpGEVdM1oYgu8ha076gOjdYmNfSC3hh/rhN+hzUvQFV+KbniSKph65rwXPoGp9inlJXSHEOnjvFurJajYITEIPtFSphR9iKQtxtJb2TMnw0/6wzqbeunXFBoiDxQSqefp7dbpa+3LnHp5JsJKFCH6qnOnH/7VMpdIX260yZDYzyBIpl2wp9gsWcRr3JSbR4bHRFBMarxhvE8l/4xTZqkBkxH2sC8mk/HCPybnTJ8S6tkTNuDW0XvuDgPAgDrwfklmJywp5FMzU/NBJw/ai5VCdOsz0q5wabpXRKLYp4d9v0CE5SrXuIzOyx03GtSolYoDLFnwjqAkRyZQnhqEGZgG8akHDyOx+qngL8LgNriG/g+/J4uNan2z3MF9puXMApoBHIOktHZmmOW/pTBD9aSNcR4nOlTb4zlUFv6EMBz/WLsRA2ancytIjsupY9AgRAhgbixo2KCZFxT9m6YLf3J4kaPt1u3JvbdUk5N/VC3HxXClJC2nw+cWZbsop7K2+HBesl0Uu2QQ9CxBQFhPF0bSPiidpjnZZON+fG2nhG4vLeVL/fJgopvf5iU1MsLYmEQ6Z7KhRerkmfPT4y0ZUx+1vOgSAIDQPXkX0huJn19597kmHxCfqVtb3B70atH4/tbjcuQYEzthvrtWIu9HpmnKg==
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: kafka
