apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: zylos-kafka-connect
  namespace: zylos-infra-kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    app.kubernetes.io/name: zylos-kafka-connect
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: connect
spec:
  replicas: 2
  image: ghcr.io/zylos-platform/zylos-kafka-connect
  bootstrapServers: zylos-kafka-kafka-bootstrap:9092

  groupId: zylos-kafka-connect
  configStorageTopic: connect-cluster-configs
  offsetStorageTopic: connect-cluster-offsets
  statusStorageTopic: connect-cluster-status

  config:
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry:8081
    config.providers: file,secrets
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider

  template:
    pod:
      metadata:
        labels:
          app.kubernetes.io/name: zylos-kafka-connect
          app.kubernetes.io/part-of: zylos-platform
          app.kubernetes.io/component: connect
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
    connectContainer:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]

  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: 1
      memory: 1536Mi
  jvmOptions:
    -Xms: 512m
    -Xmx: 512m
