apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: zylos-kafka-connect
  namespace: zylos-data-kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1

  image: ghcr.io/zylos-platform/zylos-kafka-connect
  bootstrapServers: zylos-kafka-kafka-bootstrap.zylos-data-kafka.svc.cluster.local:9092

  groupId: zylos-kafka-connect
  configStorageTopic: connect-cluster-configs
  offsetStorageTopic: connect-cluster-offsets
  statusStorageTopic: connect-cluster-status

  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://schema-registry.zylos-data-kafka.svc.cluster.local:8081

    config.providers: file,secrets
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider

  template:
    pod:
      imagePullSecrets:
        - name: kafka-connect-build-secret

  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: 1
      memory: 1536Mi
  jvmOptions:
    -Xms: 512m
    -Xmx: 512m
