apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-connect-secret-reader
  namespace: zylos-data-kafka
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-connect-secret-reader-binding
  namespace: zylos-data-kafka
subjects:
  - kind: ServiceAccount
    name: zylos-kafka-connect-connect
    namespace: zylos-data-kafka
roleRef:
  kind: Role
  name: strimzi-connect-secret-reader
  apiGroup: rbac.authorization.k8s.io
