apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- connect-cluster.yaml
- connector-catalog.yaml
- kafka-connect-rbac.yaml
images:
- name: ghcr.io/zylos-platform/zylos-kafka-connect
  newName: ghcr.io/zylos-platform/zylos-kafka-connect
  newTag: 495c0ff2b91f114043d15b78810b8500d5f58ffc
