# values-local.yaml

springProfile: local
environment: local

# Laptop optimization
replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

pdb:
  enabled: false

autoscaling:
  enabled: false

serviceMonitor:
  enabled: false

extraEnv:
  ZYLOS_ISSUER_URI: "http://auth.zylos.local/realms/zylos"
