apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-mongodb-debezium
  namespace: zylos-data-kafka
spec:
  encryptedData:
    password: AgAHI5Lw6ntOiRqkqlVwUaDIoEy4iJh71n3GiCUnfjxOednM6ubeH+4Tsfc8OCWZYHuzvrK5L57NsS439yB1It2MeacTUijECJEEMR5uR9NSUgMZ9sbXAqAdjWWJuixA4mYLXismdKSCqw2/9bGWqUYD6tNjFUHomJ2UlnRPfAWBpiBmAx4lKRhjkvAQkrPnOWqQWcZ/h2ErrnVnN4qAfPHrI45JZeOjlHKzWI/ExM9wMCinD3qFNR7nyr9cI5PZm+V9n06W27VyvmjdrptlalHx2EfnWiXUUmLHnBi8rcxzwEKtR7AEukV2+m8K6ix4EXoIN9POdfdGNPgxtHGqQpvQ3gBVGfBhJ4L1UhR69w8w7rbHomVswFdDOng5jAO2NxEyyekaZUbvBBQGOBSO0EjWCZGMFCXdnKLPBgXAVs3+gg3OaUHs7KxrNOctbrMeevxcYJuE8TwR+fb1V4bPC/5wasf/O6WjRk0+CwXjyhldnrZN9eBLfeqjj5NOd0GkqCxYRYF8z7cKxKfdqRz9Ec7akXlfA1TS6mH2tZsNYuURFFlDPSdwya2IfNzYOGQKuzqTugmXcCsTK2QGuDOGC3ZbB/5qT4yTS3ukTzE8Mvsyse+DO6re/ooVu0U/JTXMW5QFWNFbf91NYRqamFApKa5PX0p4A2FO/6EEbeVMEaus+gWMnNkHrc4gPzFHWFK6/OLohneDLA0qUxfkD8KEiOYVhkxFYZlRH/1VYMhELN3PsU5BO2k8AcYlMASXqxxNJcQ=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-data-kafka
