apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-debezium
  namespace: zylos-data-kafka
spec:
  encryptedData:
    password: AgB1GMbBS/VFcc8SwsMR83pjQuCg2JypblzbjGHx2JMiJdhZQ+hSpy/+pUITs7tkg5RgQLSQPYJWC/K/IvYorE68Twpr+6iYEGyMBUI57pOXQBKfCDbtjbT09OCbXsBpgiGwd5T+Tbm1XyNr83Cv1URhdu028dhcjhq9bVngfeeuRuHr/CG2+uwxyGIy96AzBmd56HE4NYAFKfOPzv32BSnCjWfEU8/q853H2ZgXaV+ZMGIttwR7DElFwz4lZpn6DFU0ZEklD54zuYUTqXBaeM4Mr96hdlc+ed89aXktIN+V5m6+ZrQ1WPWRjl3ofzY+EI1gnnUp3bYQ0mUMGq4+iKgm2no7MuBsDQXTjGIj5s2jOuOFINFFGB7BDUoHq21SlA9t6sQWq+yZ7O2jCbKc7cSWkNJHFE2S2yQlQ4lZOlToM4nhE9VmBvFeNgJDRZ1WxHdFV/1aQ6uj6lFq3P+9xgzS32lFzizp0UPvSdHS1vguZxEo5P/Sc1tSTeRNvkW9nJJQnH4TgItohEqXGcFcfsQwViMCve1o/B/QLL08uyU3V/FMnew9z4fbst5vk8ZwTk4LjgEwF0f8hfrATJE8a8cbLhmtpyXB2ACAo2SA70txgsP9q74cfuLfjySAesX11p6kYBP2RO79K5CXeRSXmmSWtYhu5vPMMdpbbz9AHTNSbwF1MYeWcFvmFsm5Gi95NnnuTh8sLxGH0mINIV9G3a983H54PEpp8bxwYrFVIg7mXLEpC2zM43Xg33RVMxtTHVA=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-data-kafka
