apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-mongodb-debezium
  namespace: zylos-data-kafka
spec:
  encryptedData:
    password: AgCAeLy/YJSv/F2G0YiFjQiBIsEUyshjwajCpDzOEzFzhHjwtZzDOijWCV2yATBszYm6GCIdg/Z9VnqOMpsvTtgmi+BVsbNCPsj7Ceh+Y2++pyBjFLE90YmzssaZ3rVkO7/1E2/4jSVlGwF2Eq0bIWWQjOOjcHCFiuVp0gkoifAQuaqsfIuNTIYW1W+VH2s2ZI+v+ef3THJvZ1sWxFdMNy2WB3NblErmkLjcvMHwo7QbIpXGzHtfnLHInRoMmSOaqGYaQfAMUQkiRDI8FSy5QD1LqoCHo4O2RqmLgQVhF5rcetjvs+1BVCgG/68YX82t498c5iRf9R7PF6JyxHKZZHspNS9HdVKgQxarY7FW2mM8dTRtqEuQkBILK93FQYGkOYwvVzcL198DB/HjYw8QoYX2Wj+X2ItBbMy7pFzGGKTU+aA1lhm89K0aFgP8QgM1NAZrL+F2zKE/8khtPfeJx3AFWJ0MgEsblqDK0bGUt68r2Ndj620OGN7OCr5/bw5AgFiy6DjFdM/qNaAgJBvnWJtfXlltGGSjAiGFhhf+ckzcb6/vMjVew7CcqoBZHSJ9w0Yfix0OoljGhtMKGcfmDZWP+zuFl05GKIUI65VrJbVIYY84n8Z4TKcVUV2F5Op0FJElr9q+9nVYIMYdQGuVPTkmgdcmP/4CMsSDrGvd3ZXn00qnHs/GtjmMyMFUMiaWr1L3IzPKyHyqllxc4+JjdEpP+hFDmWA7Mdxy9P0cj9i3+VHoBgtcg/KbqtNwIyL2XiY=
  template:
    metadata:
      name: catalog-mongodb-debezium
      namespace: zylos-data-kafka
