apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: kafka-connect-build-secret
  namespace: zylos-data-kafka
spec:
  encryptedData:
    .dockerconfigjson: AgBi/nDIkbnb4SHfRi68JZrXYIZgXAtT9CLfO75f5TBHJGQd9c66UGc4vV62tAcPQVGs/FjKqYby6tdW5aaKzvlv5SgaOsyXZA2OWTjfnEdS3hYxloEfV1iOnEIly+QAhzXF+HTssweNQab+sUmROFCUqtWcAXC1KSjJAZmmZLTjYVgpLUWCffGcSDnyWNM3rw4PUI6pjV29g6qGb9R7qsbDsBsDC61sIg+clDmh5f50H6TR9Wyc1CaNj322mMaqeT6HGwT1b7r+CJ3MhwIwbUmnQzG8QJ9px/IO7r9aoXHcjVJE+CaCsU+xhcXvmXTvMybaC1TgcqtvDm7KXZ+TnJb7meX5WfVqyb0DzizhZnFkDwTURGwOMQrr+GhgI9hDrq5Ip6ULObbeXyjq6wGiJsF2GgI/FUB0Hj5IQbUVIgGX3vXUpqVqkGIxb6ETakXOab79+0A/wTHQjoe5a2c8ZoRzOew9xvAyOyHlPSS9TQyufkwLJhAv+36eV3VqhK6mtT8wfTs6n5AObRGaEdJskOSnv7dG7/PNXL94I8IPF+6kp9l0hcgSM2IniPCltCgb0qDneo1CDdSSCHolLvBKEVQuL5IR7GPowgXFPHYbtTr19TPMyV1wcb8M/mzYTf9zTjLEGPv8KuIgczzQp2ZtiijenZNk+kp6Sewl3gF26ekdb+uJYrp2hNzEtzqPejfkasOecswNIIEXKrXmpGprNVDndDyT/8M7LIQE1ef19V7DdQYE6FUopNxyiQQnzJlXygadkH97hAq6UQ/+ghClLJwvk4DXn2I4IoOZTIbOYVzRps7XP7cwDFlMIxBJjVKGqkJgpUeq2uZ6bzpvISw4hZheEi0VPKG/T7Cz7KFX+H1Irpbs0+S0us59Fmj6mdz8fVMqhK1tdiBYd/uViQlxZA6fpxGVAljR1Osmh2AWjBDsKEGrr98ziAakr4amuLnkuwGp1aRzGqmj
  template:
    metadata:
      name: kafka-connect-build-secret
      namespace: zylos-data-kafka
    type: kubernetes.io/dockerconfigjson
