apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: kafka-connect-build-secret
  namespace: zylos-data-kafka
spec:
  encryptedData:
    .dockerconfigjson: AgCMybUgyhxqPZ9iTeMNBRNW3LRjq+fdx8ybHaHIS1EKigCyoC1M6H3hgfbELyEcmKQKUN4n+6eb6tYuWfM2Qv6NmDcXBQ6p9c5aRIjA7Hb+3dnyk1u7Mv4lfnSuAVxUcTGL+8qXh50ps8MVdSUYwJFI843BBGzJC4MJN9aQJ1c1YVoyGeLQOoQFK0OUB07RjB/1k8cruClU0wltzegNBsNqAmQYy9PCJIVTkcGRvdejMvhQzj2FuQnqAirZ46I7WQBEv9n0An7VZb3m2FvfqFSO25W6vRzoL7r9OnSijgElgCikzNVEUmRbA4Z1JYXVFFHAnEokEtF9tCKeFo1baj9LMs3e+J3o+jUICQmuQbsFJSse4s+3HZ+HTsFreAWrWA5g2TO7QLDOGLe9Rwg/Yzl2gPIWQuTE6ov2Z5TOYjdDgBDkVTfeGHDY4uOUVlllqp5R2b/WCW3uW+YuBMibA/wz3eOTzhlqGxj1Zs3xEMoYsQHQ4+j2+/lNRsM4Tfyx3x1f0wbUh59xZbHoUqGYAgs1lQMpLj9nyZWZnZycM1dSwCXcX5yLYJ4jy3lB+zf75o30vleWwKUYtFXTiqvyZ5066K/xE/y0knaCZ9xZgTRD20ObGOFiHcb4VCBh5tSOidn4l9eBfgH0AmSItIf08oOwvFWPWy3OoZWY8AlxkGcfftaFXmTpY7C2j1zfs0O3aQiX/MTnOsXXedrYSry8YqxKX7OlDNV+gv1RAYyIaqQNyXnxnQtfYEDREmdZ0PXrg6rVlciuwcxbirmJnLWuQq8T/C1z6UpK3fJu1ahO+ghcIz1DSk0bC2JxBVP+ESoi7FEe2YDNQ2KdGSkThGe+BFQm5kEi/1a9g7om5xqsVzosaSYpLgh3MpoEZ0UX7N8dO7G+g8Mdg2jF1Bo0KE449J5AjUO8cPFT67HwoAUv86NFTJ+aHOyoyVNJSbRDUcSzzhYBx39D/T9r
  template:
    metadata:
      name: kafka-connect-build-secret
      namespace: zylos-data-kafka
    type: kubernetes.io/dockerconfigjson
