apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: kafka-connect-build-secret
  namespace: zylos-data-kafka
spec:
  encryptedData:
    .dockerconfigjson: AgBYjonxZJnqzA2d9SfaLlpQlxNgbgTC0AaznKYsgXRu/iRkCCvL4zqayWDr5nhPUW7nZMhoO+xXU1pEOnQFa5kPW17ZUhyhSAIrMC47HXMw3inY05GoIYxvjsC193w6a2+KgwVN6qoZPo7qDDUPCWGqTJZYts374jvD1cXQDB4HVPSYyu8L8R5amdJc1xIRUYjmHuoS8gjZncgkyBs+8iJDWsV/Tu3a14GzBheBPpqOFNx0bAGp1jWbpj3CdGhoXxwzxht+dIV+YkPgCNZzBXeniYUkY86ruhqL4beXmEwsza2a7Il44ZcPSluE/3XJ/QdZ+bqezJjsePUo+jxKopxOA+nsBrQLP40ugLqgs/Et37CZ0OyMcOgquFtbEIJY0QhZfECIPSTr4lSxNzUwzDPuB54MqoTNVutaEVT1f5aW6lJ9gDVp2CqBlJxqphdEp23A6d7eqpios35+j5aYr8ZfhFBdmHEGbmj7bzF6OThe8v3PYB3bifhAWoFT9ITzs/nTzZzZMJCyfL+5Sq7USzACwp7yLbvW6HkXF6xlxszzKRCDajQ5gxJAeQf0XCTR8pHz5uTJLIvMWcjerFe913IJtEoCDhjsyAjnu1sg721ptFl0FQBJYmBTx592mUvoIWOe6Hxaly8Ip1NyAvE26Z4VmAb/aehEH2DijK2xdXxm2gw6hi9dqCSCu96edZV34dmrdSWuFPlxrW/AwK0Fa+eswRvpYYwVgCdx7BeUXs+MR+ssT2jpm5IJu8C+mrYvGz1+Q/acUbKf8RRkJU+vbAZTcK8xvQw9QN1ldPjPWYW+rq9UkkS3EO6FoHvup48F1RDpRT3WR9abdfGyujD+KW8UX/7w805zGLI4ex6WwJOC9Xau+MfncC4fVIqPmquVpXtJgGLwpCDBC6uq04iAjdug/aJi958Y0bLbH6FPT4eQaV5hc82QmLMwLa6L8ofI5l4hcG5afYE6
  template:
    metadata:
      name: kafka-connect-build-secret
      namespace: zylos-data-kafka
    type: kubernetes.io/dockerconfigjson
