apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-app-user
  namespace: zylos-catalog
spec:
  encryptedData:
    password: AgAagI3xDc1cA1fsvBMu3naCVVo+vKv8WCcvzN7cu6lY9MJHo9QYpMRSPVKWpnEngyYdv+otb/95vGG3r5I26n+jMlyZvskiIUmRI0PAXar2TT3mQtrTKcYbJvAiBsinRHzOvg4IiDM7fEYn+Nt3q01skvEyvvGyxJLfJq8ED0m65YtzpS3N/SU9tnzj6Uq1zzXQeF3dbV5BRT+jAAGtdpAiHNOaB5K8wdkD8VC3cqQr0iCDDZuKz4cEGWGpoDHnVEun4BTDIHfmJHQ8ZmP48jGXatZTP9xxB1U43nGsuAuids/pGNLZTwaeGxPDybidk8oSQTvTmpETWn4eN55cZ3k5uN9USCR4uB4hRo/DPt3kKCumjEnIvp0vL5fbqJzQ19feKbu7i0rLRQz1ApBtkmDbk+5Eqwo6xSkw0NVpuiX2UGF4XjF2vkzNvF7r6qAzzBeFBW9R0xWhsBP1nEtT0deEMPnKmLqQ/57QFk/wS3AMs41uFrs8DBKUo0AMEoVcmennk361TrwUuy6x8/C7oj0BV+WWLorZrQxz9xXXcdGZU5ZxpS/G77eF4hQk8T7GBVABu2/XLswTTHQ7HXelt0Z/brcYl1vcD9/vqB2Codh/RuHKF2bZogGzJCKZ886CLrDkb1k6+m/UxabmSvvvbfsZezatFTALHmijn5p9WzQTeaKpJEumqnNRIaPBM+ZDbBVBRAEVlSi84oQptJ6O+/35n+EiXOfsl72UNkDtU2gQ7bGBDEEydOy8LwSrZmVkkaY=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-catalog
