apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-catalog
spec:
  encryptedData:
    password: AgCkyCh95uI/XkLdJMZWSCg+jJ18TDd/bm4fo/D9WGhV+JtEjQTvTT7LtoYzIlmIBjpQsBhNJ5iDE5K6cPYcI88CBoyWlr808mWcaAvy6cP+G6wv2WTT3uK1LxfRX+/k3v4F7OgUBbyTxUY4wgEBlzYfcIQ5/kIHag4j8KWuraaoO5XMyHaqjQwRKnjaBlxSHEArFlFT8UGBOO0fSK/IUWjyPBzPP22OeGsHtVqjOWYcniSG+AZzT/+5TsguRNqRs1EXLywyzMa5aXnvJzELEhl9B4hWUJRZp1nlNqgL9Uwxy/S5qqqbgu/1YkkSnWV7IWS5P9lesIwSWUvMsYyC64OerJ7o8WaGvmtJamY01dCoikjv/oHOpyCeAZITNazWvUl1CzHvIMoYWXaWr5F2q3fV4VEW3E4A119oNjuYwuCUok+7nKuSh71pHZzHRRx97kUXH50pv7XH9f69U5A/lZ7q1iH4P1naDP1gsYFjRQ46wdOxWLuGU9ZFlbh5BRcSJWoR/FRjpKceNo7xSlyp7P76H+5NTpBO1r4x2GlclfPuOgkQ8dRBzi6OuuyWaWQJcRTA/rWS/khzIj0Ro4vHbKV6DLdhlznLte8Haiq2eYIB3fzjvsXQJPcDDn/cI5Y67A9XD5vHKOtEpKN7sL1qMWR+No/JMLd2KU4L0vu2bHDf0TurKDwIAemfC5Z/0exn/kl3i15olscX3j3mPjtV+vretZBEhdLkSzmXSFXw8MW45A==
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-catalog
