apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-valkey-app-user
  namespace: zylos-catalog
spec:
  encryptedData:
    password: AgAOiEiQ7MvAhQJRHYn+keXSSDJIWqcVuzPxM/AkFvujgVdXNPrjCo4GHtd1Jedvi2B2rp9RpxUp3Oco7RlDtyZ61OMAdg360H8ikzfzTCMWHZ9sI9wwZt4K6vap2YPwAbSzCqDLRHe5MXBBPccNVTfbT1A3NmdNGwFiPP48DI0/lMOjkUggD7BaSRFptetIV5dgeIy1N9b3hzadIJcuePsrC1qYzHbGpSEKM7gaBSRUbX5HkvLPU+1fJ47UsKuK/xPpk+WTkR7CichsvGwgSN0wVTAwsLX/vZMsiWWRz/erxO9SLfjmyf8QfztceXarHwGfrSY8ztofCwt8hRaKBmggQd8cIXPol7DMSYxUSLMa2sYM6hP01R6gzbOpWu8Icg7HLF3yLXGfA/0tnPs6Icisb6jJfxkhMskocodgrzvt/4TLiTbKcWJZHM9Kx3CwFJDwZo+eicie1iYGUpLXIhJxTjbgE9mkjvjszMuex5QrBChVoTWJgkXA3D6J5ymnafCDG/awbFrQgi7UgKK93mQ9Csv0ZzPPuAlUthjRfSdVk3OlxiEccrNfwSFFObzBvg2zMHM4fG0fxkbEnYlk/Wwi1IOD//jMph+MPYeCMb1oAH0VuzHkOWQeQblxAAcXyMMADjNRSWbfWkzI5sKTHQaf4bQwnhZoyWwz3ua9WPH8Gsdrc6wffymaii2b+jVE7Hi6B04O6QqMPKwPa5yYN1qcKghuUaszVSx32sO1PFkGki9IO/7PBW/38qJatZ4yUNc=
  template:
    metadata:
      name: catalog-valkey-app-user
      namespace: zylos-catalog
