apiVersion: v1
kind: ServiceAccount
metadata:
  name: zylos-service-cart-reaper
  namespace: zylos-cart
  labels:
    app.kubernetes.io/name: zylos-service-cart
    app.kubernetes.io/component: reaper
automountServiceAccountToken: false
