apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgBbunq1RvRlCWosXcTgSRBZZTch2Bqub2tAL064Dzk5q5a6djvUHUMlbRdVKOPA0jbfBZ5+qwBAzT9gfKAav9HSSbxUjI7TjQ9waAGzbJfyOvfkbzCJwGMtgAM/Beqww7ZgwLyvnulcVPaBkuUkApk9iixVZRnt2kodnzouv0fh0k2rUApV123G9hH0qPSwk44ix1xdBnet0GbmZr3gbSzCdpwr3YToetEE7v/UGfQgIaRG+mpa6UT07FeUlr3w78d8t9721Jn8+nMNGnBZjeCn0ubDawr5eDLGCOJ46QOmSyrmj0B+cw8mbkUU3FoXGCV4wzqXmwUI5RMNj47ZeeHPpLz5a3TNvribs+uh3BJtkKah8tPk7VFxKjHwhOVXpcU5icUZR78/daxP97AkrARJZXtzbUaPG183yRt/DaSguF/xXDxqX0VenwYttgO+CwbFFR6i9k4yHV54Qe23uzmz9Cx31XS3M3TYccXf4lwDJoWJug4419V/refmftZ07AI9VNR/clkhhizHwBSJl0RXzcJp2jjpxwLzW/olinYLJidOO4M94tYduG5P8uGYhYwnEtZH4T+qu2dsk5v/u0MXGyaNV7uiJ6OvL/KBmzIqhyS7oNeus17Dd6z805bEeHYBLJw20X0t/d/6x7i+7otdltmSXeM/cIqTGTxI8AxUzI8LqlDjO/a+YsRrHo54ZObWY6/o8X1C
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-services
