apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-mongodb-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgA4cq9ERxnoguOBp76MyeY0C9WiUT27Xx1hOar+22j4RuK/KF9/Cz7lBk6xgs0tVyfFWrcnKlh9/4VfBSCm6kK3Myj/LE3vbztmRygPzCG/7R3W4qNhLVje6xt9bsKXe5ifT6VsdmkP2CmWhXhK29+aw/AFLfpoPz0E4TpmA/KVaF/sd/QX2j4Au2o5CKM31l0FjyL1PzhrNGk2Hh7ygZlPYhm0KEl/jOzdsa1JLRxR09ucVRwwm5U7mCRP7nBed+l5fno2x6NEYXzYbEByDVqTiDEHSx7p8mqMs6olohSnliVuRJL7sv3FTRsbM0Wd8jTQX0Kf2pGEth7T9JCdN8rEfmxskWTpO584s9wIg+uwOfhbiL/KL0Fh9NFNfIzRibZIssY1xMlKEB4UMFdV29S1wLkeDJOJ9K5IvjPfxb9nCS2Z5Bk+74OGJ8Cz2nQZHCepTj4UORLBS7UYR+GWLj75eG7LNKoFlJsUf2VstRKh/4ENl8XiD/8U1NAVGQWTY/01+z2Hd8YN3KmZglVGkO9LB31dTn9p+HnZaFhHvUTyC88LS2Vo1DARjdaU04gHd8kaKJbJ+meEOTVdHlWMQFh/WFVDOQyAREEJbe4OXPJWNd1x68zfC7+6oFsqkNi4FofdpNf8swSp3W2itCKGNQ7nD6Ww5VF0DmAHfNSsRLejBGG2AioZ6RcwtT2KE6kpMwIFqybuK4adfGVLzAdb3qXQTaw6ablOMt2rWNhpgzXXAZpkGrTY+o74grq2tuJNxdU=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-services
