apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-valkey-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgB/SA86QOITjcV4x839yp4VyJtYYk646YKLhes8PmvlcswLgsnSc1a3Mndq7zm9K7VyL++OHHo5hw7WKmwhNrzJZ6z1gmBFJZhZU05oPh1hsDM4zOfdSwlqF8TXRKTOyw+mo4TyiK1//URCozlW1XJ6fzfMs+1VCIMkdsZqe117LZhr7P3BDaBsWEsJhGvxnXIws48A3BtpBSowZg4o7BVmCPa8iszgDsBo3+fcDTXXdPQTRXJpbeOExH4ULO2sVFPJoyy9ZW5hPK2U32Y514WyIQpm3Bn1WM908YBsrDHgpgSFwiy0Qsj6Q6UnvuCUVLzJVQommK1ftWAtZVDGR2WhB50Foe1w0qRRI93T2Em+WJwFL5dVckj86fj1WlVQ1iD5LeNogrGgv+nML7LJ24/RM7PsKFJdmBnEq66gHimz68HQvDrMEch4G0DfaVpqA8W5hvyTLvpTzrhbB/u73p2WQqe3kBi4+HvH563v4uXsJOXcW/+/LubMg70Rn52jalEVEn4OiE1GGODaXmtOczscCmq8HbflbTf6jpFCRmKj8UkJ7ZHeMShlIAjrWi+zRi/i3Medf692xXc2s4d4lPZtu5I626SFL9AsxRIbWjKh+25YKN5ABzpfZF9qOm3ZToSW22gtRN7Egabmtuwedf0MoHb95VX6MVe2CobR2AhA7JE+/dhMz2ul2zAJ8BRFR8+axI5cl+5mj5ah584a517SuzxvAjBC
  template:
    metadata:
      name: catalog-valkey-app-user
      namespace: zylos-services
