apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgAjMeLhmbjJfcou+ErYMjiJW4n+SO6IBWfm5ucZGKZ2jEf6vuK9SCLnp7h7UR+o3WHXmLNL5oM3mCHREugyfjSJGHHA3r61LxaH/9duxNwk4KbCg9fz4Dg8JoxLoSj2Gv8FE3Fqd+PhyVwORHp4X483W8cABtY41VLR/ocu6ra4gmesvsIJpqGdL+DF9MQiRJkf/HVeAjGb+PZ/y1B0j0GOIhmtPEqctdv3LffN6w8cSWNpRXW1VJwdcOUT4z6n0oKsRxdeUt56wWKHMJ1FCozgy4pGldCG/gMxINOLKZflD75et9MeLUHlwc6qoQrK3yEVhtiWYl27fhaBwfpVWx1jozNIpyfsDfoq5zf64GVSO1y7zFr7Bzmk3D2JKxt6aJ47BgatEpOfxwvLeaG9XPbIcx7Hqs0nv6JCCS3GJ98fKCK9jeYPfMz1S5qB+Ldm+tcfnBy0R/sqEpDLVKe/neMwd5h6l1d2kiTJsV6vVel5YE8MQpuoSX+AnQlQydxw/c6ALnVqvAGwW3gWp6pYMVfEy+G/bduFJp8tcgK/XDRENm43Il/VCM6KPlc44NYf5abbY+zClPNC8U/4IAD14ty/eMh2XIqdH7uKMkfX5AdloE/ONgo3k3KnqTcqrMrsGNZKl0TmJq9M5jxu2B7Q54aDA9WHNbCJlXK506MGvdT/BTxz78IcgZOK+uRz/LRH7C/T4Dtqh+bUyzdWXXoo6ZgQmg==
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-services
