apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-mongodb-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgBPjP8+ws7u19/d9vlTmIXcgCfABVt/ZVk0H/stgY6ocOqMB5kNmO43d/zFfhwFLRW/9NZMJxopmak2+A7/ENmcIgHYQqXjWenvUIBhgrUMPomcteQXB/jvHIpZtFRyBvaMzLAJeZ9olfMZQS8M4Ed0jWzCczB6bUlFtRbiqtfhsNP3YhcT+32r9Frw/KBWmEloN91XKIJTJgHsGH/J+JjTlmX0cGYlKRnpxAAHDVZD509znEMUbmtCUPRfsl/wwbbWVvbK3lTEJhXi/k2lz+fQbcjCMtGunaXrCXNoC8pLsAaLSTMIETa63jT3t+keUdqyVXryfa9rATM2wB3NusLaq/8jI/npmFcai24CWLPui+P/0M0aWI+xvvF6FcUjC4zQizfsgMY5NhI2gy3qwBi5J4AgCqpxryXVg2uvo5DUJKoU79Dfz15gioCr8/0gtfvpQkZXk/ZNb97tjz7dFFGgJFz5zwvfMJ0mQr8wswvacLGXtDz5s+PNrKBgrrMpLgufuK5yoc2eAemn6sNvmCJxUE9BsNL2bbq/zgwb7BsyQz4LXq5UDJzeAkI/pfTqpVNNuErSbLHyqSBX1CsQMV+gYZwg1/DqrHOBFZl0XR9GqJpTnWtNxA9sHXfdD8K/T3SjJFj91jYhtUahzWlFJJqr35okCLpcCsi2CfIO9Ffw+w0RpsVC6e1tFyy1tId5Fc3MW36yEMB49B3q1xaedv4JWPb7K/jw+Nev5j8cEZukz6U1plCatKU6LycWe5+wnK8=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-services
