apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-valkey-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgCbnJiC2KrnrvbkGDWUll5xDb3naH3gnBA4XhaEycBxZuALfW+fkjvN+hlq1TJ2wWuzTNOfg3dvx/fkebUjIBFfSVTAY0cO1SQBmwTUxQbNvUMDIjooCUjxBiPiQECrumAIjrIlljQJPsEsp29uYjOSSUsf235bS9Pqqy9ZxsQwU08HTgpADBiQ89eKe3d5KO/J9IEU08wOOQ16963VyiFnCrKKnEuGmU1NtGtCPTP31L01avHnVer87qPB8HnDznxXhKUz1TaE+4mRAlafalefnMhbCjvpcMuGRZ8W77rklXZwrnqZXVG9tX7gMkOk8DeQyG7Ak/HZQwEbdGLvDUZGPZFRmTaaywEstNwI/oWdorIq9vdujEsYhpM1J6ZSmw1HpcwMdKRUdq9uLxrDddJG0tvJe2T7dMTnFNcoKefNgHUTbSwbx2/r0UqmRu4PLnv3YUt7CKboe+NmeFZbgQY6NxKPgi4HLjX/DV3wTuLpirvt8Wa40r6sKcA5Pl8qZRfn+SH2InXNnQnjX+aKee455kabDAjeZy740xZvpZ5Z6WpCzTR+0rg9z5o1uXakks1Bguhx5YXYheW2VvH2sgDaSGVmtFQ8d00PTaLInD+4n3Mv4Q1sPO3OzENTFYSiSk+vuGgnQnUEi8Sia+tYruAppIa+nPqewwv/QDQmcLtwrLkDjgc5VbYJlZzvXqGc+RPBcXHQ1Cv70dzOHcB4lX5IzuSG118k
  template:
    metadata:
      name: catalog-valkey-app-user
      namespace: zylos-services
