apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-mongodb-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgCn2NXR9OP6dR/QvHsDD+/D/JRZ/iHjJYAKoFxH5Q/4qZYHTNpEP9xkdk94Fd3bgPNPPGL7Cp2luAoLq0wRxG7gqJpEvIfT7qUaDeXkY7zyidhCCkLHzfMIollj4rVUsy5DFBjApIbpYuu/tDzYpc0P5SPmGHIGxt6qwtpz0Kph1OV6W3TkdEKfHknJwmouUcU+hkYMjIiumAIId9e0IYiVafHvO3CcU40TqseiyHKQkMxXTykP7JilCKf7I2l8NLgPxBV5biGV2Noj2W6xojFtqoyBh6P9T13uAehhbdjxS4o4ewYbFAqCdlBMWy6HZUTIXI5dFjS24b7Vj/M9K9/vmDYrPnKzQTTuddZeNoySTDq6vawWay+d3pPZjix2O+xiwZBZSVrFfE3ATdexNq+dXF0laNq1Nr6l+ypLAQdBeV+TeaKaCk+UouhWckb0QtRmiTxTh2zNbfvKnj4QI9jMp4iTW8jTLl1zqI/2lWNs0HoQduuUZ/SYu4CjSLllmMPVhmqB56TfAYH4imI/HEGWai5S1KMbu7MW7U5mw4LP9iQMvmwxNQaKvHrloUimRJexZafxOX3EEeOMgLB5TYJMYgN14gu4oyG2/xIw4JzgX1amwMur6YuYhpk3x6Eaw2jSYd5hyXf7Dqcbpg8zWfPwOeHPuhyeKc9xv1TnOJ/fvJ59tpcGltaNkzKIp84EOEM+yT9GVsfg2nj2Hygh/qlJPlMcL2AJ/Cbp3IRibH8Gfu6Jf4tmQrza3nh4VLNbVi0=
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: zylos-services
