apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgAPd6srPwuIcVhTtPIFymqxpTWCh1Btlvwru/odk2+nA6S0TEaHYRLWSMG8oeBIZAsiTfgEJPINupuugGz5+JQULV14AtwBsbhw7ZO1TD9CfR/GRZID1bakIXHI8lLxrjnq6BCzBBVuVBCzhD610/V74CUm3Hp+9FxUg4FJWIXPsewyTKLl2b8Q8nKS0Tcu8BgeOjUzSeReNciVEvPVlH4CREkOTVXj3soVJBJVpbIihmiY4oyHagVY8Z4UfaGxIkeqbSIk9LFZz3f6jbMndsf9QcExx7xTPQuApxit15i+vphIiXuN9rAURT2XuNjTEEiC+pzjIIsK5yHESLDguvCOmXMGOx0G7vYVbybbhjlI+ut1zvEfGAQExBeI4Q4OgnwlvMgWvQbE9ncyxfASbpN+xGhiOMNrMHvQV8MpDlJJkl7If18CkQY77deH2kSMk2FQON3CteMeLBIhrHoBm6RCjM9KvPqXIQ78mxF1NCo6F82oT1mt+jzn3jQKnsv3XcaXkGTJUKOlAAe//zqvQYOo08CiAomG8FAYnthZFvl9gK8hBJU9ClSv6TTi71jQk1dX+eJPZfGXSyMnYFyU3cEMFgWYKbhAjZXRVicZkYxKEP5JPLOADE10h0GoqyF6yQ13x9E+klmOlZSWsRQvtjxGEd9yU6svLv1udnAWLzHd7WE+12vLHQHwtzU7UewsajcCZ+DVOVkz06eiNLPPFooj0Q==
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-services
