apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: catalog-valkey-app-user
  namespace: zylos-services
spec:
  encryptedData:
    password: AgAT6HxXSNAuwgDJt5fpFLsMEjVyxP1jr95tbuRyEN5EwkrS8PrqfOPKa2v3epDRyi8z9wH09iQEnQLNYE+v/Csr4QrTqQm4YbLcf+4IV2mRkxzxrfwT5dPebbTtHPXWPGE6iVOh0GNo+GhIxeTaVJ/s+WB6/vl+sbV7eGDLqt/du9bkn+wTTtfn9W44md+zY2zrYfZoz1Qar8F8D1EGh3RhLeuN1tbmotAAEZiRNCDD7ju6WOuYK5litHrGnrdGWWpDp42aTBCWtaiKzbZzp+sgDZ6JZuZnUMT2+8mX8Qm/VhSxUNpQ4w+Ja5mSnfwSJ1JIluUwOge5PwcUxXQJ57bKlaCqUGs7xKJv4jW0xayCxaE+3muRIl7f03Gc0pJ3v8nsLA7asDSnQDknd6h6D96QbEx1xrDT0Qm8G7qjwsZEk+xVbwL6j67taZNX0EhAlzRt32f0Ghi0p76tciLKVaNRc0hp9e/y9N0/f9l2sGOVmaFdM1BG6eY3OAcVpIZPpBF6LeE0nT1NKjnHr+lcfFULabbjVFWc++Z1fcb0Un6w4Trf7RCgSuoFRPYntav0FInFstfMEEznTIArhG5AyHDIsQJA4QDWsxoizv04XCWChM1h72PSd3ny3VrFkt5IHISb/ABqBDKAQJQO6a/MisoIeiW9vlc8jfgzIER/HpWveBDEAQvURyvge2tzmgxAyKvjoq809nlXb+egSevY1KltdrYJ+4qC
  template:
    metadata:
      name: catalog-valkey-app-user
      namespace: zylos-services
