apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: opa
  namespace: opa
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/part-of: zylos-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opa
