apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-default-deny.yaml
  - 01-allow-dns.yaml
  - 02-allow-intra-namespace.yaml
  - 03-allow-operators-ingress.yaml
  - 04-allow-mesh-hbone.yaml
  - 05-allow-node-probes.yaml
