---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-mongodb-app-user
  namespace: mongodb
spec:
  encryptedData:
    password: AgBknxvagS+6Lk1KQ1SzE3GUYTSiGY3/OeCTn8VV0lmd3xsA2o836ITgepuR05IuWx5TwPsTQ5lxHoEnJmzxI4BK/GLgnwajRREYLLWh27Dc6S/PvTPpfpmNxRaYyJbzaP4iA8xOgM6eqlflTitQhMlFWHGkRkrEbjYBvioil/5Y+VhZn0ZeG3Cy2Le6JLXRlfACINF86i+NdPMZrZOM1YvaQQ6XG6P6UDw5CeqWUX8A4Sj41pvksTF4LjhYmMnGNKEtCHRmvCl5i7ZUWeNAI7zkcuMEcYcI82gVaRbDcjrgS2PJXgzPqTiq2oAW+xvBZ4cPUFP1bs2GDmD60mkP0axSBDMQ3WXhee7D+H+9nzGrxQHLEvdXA8nqKHAgFP8uwl5V/A92Bdf9K83VoKUIqCjQWwKmnaxL3YvJ/RmnlJs27EDWvOF377JLH3OLbgKGPWIKYuJ4XQosx5Ty21PTGnJxiYzKWhPw3NcxGPbyfh/M1t8Jxhi0IcWBlWgYCybZB+DQwdgceS1Fd7uBPvGsnxhmO8JKRhpykbLR+WXAPy74VPw0Me1rMkLF5dkGR4g+o69AC3S1PCD5B9PHmVidgUEYkScOv3NcDALlIiocsSWJPnWbbeP9LnOi8tOKsbJ2hxQzQ0A5qZLC3scgQa/fAJkuh26ff3G6qoTOf0QOLvFrm9sZ7GL1ZEC0XgiIkSiWkKkXdPX7HDQkVy81j1wxps4eQvc2/eoL53i5aPfGgsCmpg==
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: mongodb
