---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: catalog-mongodb-app-user
  namespace: mongodb
spec:
  encryptedData:
    password: AgBqwSvyj6YienTN5a+TRFntSp2ngwNh7OuYR+OF6mKdqvfpZJMD58NtvnSdPcMgNacZb8ksEwWI6EGkfVwgJyw9dhRoJEotcpor+fo7J6j6wsYsBo/Nyr1JEhcjgSH1JRX4xy3XnHhwn/zUpMKdLDz1RViKMuIbQSE3KvSNCeiT/C/mI4+W9z6hJE3/N2sCGUL7nGCKXjJQw9NOqvzNgEmIdGgeeXOJvZU5EiC9qui3LGC6+QJXG6EykeUQqn0XESNmNLRFceC9lsqAEmljYOJMfcmf1OllB8ILEx8lq+U3eqED0PEX+xsD7ljjUIN1my8o9z7LKoiNr/9ArHQ9bhiwYcorrh0NZyHryfML/uncr+TQHOYX3q/AX4z/izlZhkg6MKd1bBvNMaPGIyvCyTQq+XigJwdxzmxGaHrcFvvEuHhnjKzesPYn6x/zHv3IeaaBYK51QP6GXsB10PCOnbgxJ5dhHA0+6q90iuRi2HivARwKJQKLWjJhHLMdEarncKhq3NrXV7EWL0kKc50YSafcUvGemohDLQqTePlKsjCRbsh1ZV9U+f5Qb2bQA9IqbnrqdMhfw0sph7OOOsedHZ1zKuQYGGm7oiZRB0Jm2pYdnKMQvRykwn/D7VI5NDfE3gKJp1lfbt84jqyRciJkBJovAGxn/8cBXfvUjrs98uW7X1RBRb2VUvqq0RCkdbXoTp3WXZQnEHGCgUH+MrTPMK61oQRCLH3c/tajkS3cLxlEDg==
  template:
    metadata:
      name: catalog-mongodb-app-user
      namespace: mongodb
