apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: opa
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: authorization
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opa
  ports:
    - name: http
      port: 8181
      targetPort: http
    - name: metrics
      port: 8282
      targetPort: metrics
