apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual
  namespace: kafka
  labels:
    strimzi.io/cluster: zylos-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: "1"
      memory: 1536Mi
  jvmOptions:
    -Xms: 512m
    -Xmx: 512m
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
