apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: schema-registry-specific-ingress
  namespace: data
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: schema-registry
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: zylos-services
      ports:
        - protocol: TCP
          port: 8081
