#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

# Check if the token variable is set in the terminal before running
if [ -z "${OPA_GHCR_TOKEN:-}" ]; then
  echo "ERROR: OPA_GHCR_TOKEN environment variable is not set." >&2
  echo "Please run: export OPA_GHCR_TOKEN=\"your_ghp_token\" before executing this script." >&2
  exit 1
fi

OUT_DIR="manifests/opa"
OUT_FILE="${OUT_DIR}/00-opa-sealed-secret.yaml"
mkdir -p "${OUT_DIR}"

echo "==> Verifying sealed-secrets controller..."
kubectl -n sealed-secrets wait --for=condition=Available --timeout=60s \
  deploy/sealed-secrets-controller >/dev/null

command -v kubeseal >/dev/null 2>&1 || { echo "ERROR: kubeseal not installed." >&2; exit 1; }

echo "==> Generating SealedSecret ghcr-opa-token (namespace: opa)..."
SEALED=$(kubectl create secret generic ghcr-opa-token \
  --namespace=opa \
  --from-literal=token="${OPA_GHCR_TOKEN}" \
  --dry-run=client -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

cat > "${OUT_FILE}" <<HEADER
###############################################################################
# Sealed Secret: OPA GHCR Read Bundle Credentials (namespace: opa).
# GENERATED by scripts/seal-opa-secrets.sh — do not hand-edit.
# Encrypted; safe to commit to your gitops repo.
###############################################################################
HEADER
echo "${SEALED}" >> "${OUT_FILE}"

echo "==> Wrote ${OUT_FILE}"
