#!/usr/bin/env bash
###############################################################################
# seal-keycloak-secrets.sh — generate SealedSecrets for the Keycloak instance.
#
# Generates the SealedSecret resources for CloudNativePG and the bootstrap admin,
# routing them to the correct environment overlay (local or dev).
###############################################################################

set -euo pipefail

ENV=${1:-}
if [[ "$ENV" != "local" && "$ENV" != "dev" ]]; then
  echo "Usage: $0 <local|dev>" >&2
  echo "Example: $0 local" >&2
  exit 1
fi

NS="platform"
TARGET_DIR="components/keycloak/overlays/${ENV}"
OUT_FILE="${TARGET_DIR}/keycloak-secrets.yaml"

mkdir -p "$TARGET_DIR"

echo "==> Verifying sealed-secrets-controller in ${ENV} cluster..."
if ! kubectl -n sealed-secrets get deploy sealed-secrets-controller >/dev/null 2>&1; then
  echo "ERROR: sealed-secrets-controller not found. Ensure your kubectl context is pointed to your ${ENV} cluster." >&2
  exit 1
fi

if ! command -v kubeseal >/dev/null 2>&1; then
  echo "ERROR: kubeseal CLI not installed." >&2
  exit 1
fi

if [[ "$ENV" == "local" ]]; then
  echo "==> Using stable reproducible credentials for [LOCAL] environment..."
  KEYCLOAK_DB_USER="keycloak"
  KEYCLOAK_DB_PASSWORD="kc_local_db_pw_2026"
  KEYCLOAK_ADMIN_USER="admin"
  KEYCLOAK_ADMIN_PASSWORD="admin"
else
  echo "==> Generating strong random credentials for [DEV] environment..."
  KEYCLOAK_DB_USER="keycloak"
  KEYCLOAK_DB_PASSWORD="$(openssl rand -hex 16)"
  KEYCLOAK_ADMIN_USER="admin"
  KEYCLOAK_ADMIN_PASSWORD="$(openssl rand -hex 12)"

  # Print the admin password so the developer running the script can save it to their local vault
  echo "    [!] DEV Admin Password generated: ${KEYCLOAK_ADMIN_PASSWORD}"
fi

# Generate plain Secrets and pipe through kubeseal.
echo "==> Generating SealedSecret for keycloak-db-credentials..."
DB_SEALED=$(kubectl create secret generic keycloak-db-credentials \
  --namespace="${NS}" \
  --type=kubernetes.io/basic-auth \
  --from-literal=username="${KEYCLOAK_DB_USER}" \
  --from-literal=password="${KEYCLOAK_DB_PASSWORD}" \
  --dry-run=client -o yaml | \
  kubectl annotate -f - --local "argocd.argoproj.io/hook=PreSync" -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

echo "==> Generating SealedSecret for keycloak-admin-credentials..."
ADMIN_SEALED=$(kubectl create secret generic keycloak-admin-credentials \
  --namespace="${NS}" \
  --from-literal=username="${KEYCLOAK_ADMIN_USER}" \
  --from-literal=password="${KEYCLOAK_ADMIN_PASSWORD}" \
  --dry-run=client -o yaml | \
  kubectl annotate -f - --local "argocd.argoproj.io/hook=PreSync" -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

# Write the combined manifest.
cat > "${OUT_FILE}" <<HEADER
###############################################################################
# Sealed Secrets for Keycloak Database and Admin.
#
# GENERATED by scripts/seal-keycloak-secrets.sh — do not hand-edit.
# ENVIRONMENT: ${ENV^^}
#
# These resources decrypt to plain Secrets named keycloak-db-credentials
# and keycloak-admin-credentials in the ${NS} namespace.
###############################################################################
HEADER

echo "${DB_SEALED}" >> "${OUT_FILE}"
echo "---" >> "${OUT_FILE}"
echo "${ADMIN_SEALED}" >> "${OUT_FILE}"

echo "✓ Success! Wrote ${OUT_FILE}"
