#!/usr/bin/env bash
###############################################################################
# seal-keycloak-secrets.sh — generate SealedSecrets for the Keycloak instance.
#
# This script:
#   1. Verifies the sealed-secrets controller is running.
#   2. Generates plain Secret YAML from the dev passwords below.
#   3. Pipes through `kubeseal` to produce SealedSecret resources.
#   4. Writes the result to manifests/keycloak/01-sealed-secrets.yaml.
#
# DEV PASSWORDS BELOW ARE FOR KIND CLUSTERS ONLY.
# Production credentials come from AWS Secrets Manager via ESO.
###############################################################################

set -euo pipefail

# Move to repo root
cd "$(dirname "$0")/.."

# Dev-only credentials. 
KEYCLOAK_DB_USER="keycloak"
KEYCLOAK_DB_PASSWORD="kc_dev_db_pw_2026_change_in_prod"
KEYCLOAK_ADMIN_USER="admin"
KEYCLOAK_ADMIN_PASSWORD="admin"

OUT_FILE="manifests/keycloak/01-sealed-secrets.yaml"

# Verify the controller is reachable.
echo "==> Verifying sealed-secrets controller..."
if ! kubectl -n sealed-secrets get deploy sealed-secrets-controller >/dev/null 2>&1; then
  echo "ERROR: sealed-secrets-controller not found in namespace sealed-secrets." >&2
  echo "Wait for Argo CD reconciliation before running this script." >&2
  exit 1
fi

if ! kubectl -n sealed-secrets wait --for=condition=Available --timeout=60s \
    deploy/sealed-secrets-controller >/dev/null 2>&1; then
  echo "ERROR: sealed-secrets-controller is not Available." >&2
  exit 1
fi

if ! command -v kubeseal >/dev/null 2>&1; then
  echo "ERROR: kubeseal CLI not installed. Install via:" >&2
  echo "  brew install kubeseal      # macOS" >&2
  echo "  See https://github.com/bitnami-labs/sealed-secrets/releases for Linux." >&2
  exit 1
fi

# Generate plain Secrets and pipe through kubeseal.
echo "==> Generating SealedSecret for keycloak-db-credentials..."
DB_SEALED=$(kubectl create secret generic keycloak-db-credentials \
  --namespace=keycloak \
  --type=kubernetes.io/basic-auth \
  --from-literal=username="${KEYCLOAK_DB_USER}" \
  --from-literal=password="${KEYCLOAK_DB_PASSWORD}" \
  --dry-run=client -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

echo "==> Generating SealedSecret for keycloak-admin-credentials..."
ADMIN_SEALED=$(kubectl create secret generic keycloak-admin-credentials \
  --namespace=keycloak \
  --from-literal=username="${KEYCLOAK_ADMIN_USER}" \
  --from-literal=password="${KEYCLOAK_ADMIN_PASSWORD}" \
  --dry-run=client -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

# Write the combined manifest.
cat > "${OUT_FILE}" <<HEADER
###############################################################################
# Sealed Secrets for Keycloak.
#
# GENERATED by scripts/seal-keycloak-secrets.sh — do not hand-edit.
#
# These resources decrypt to plain Secrets named keycloak-db-credentials
# (CloudNativePG-managed Postgres credentials) and keycloak-admin-credentials
# (Keycloak bootstrap admin) in the keycloak namespace.
#
# Per ADR 0007: Sealed Secrets for kind dev; ESO + AWS Secrets Manager for
# production.
#
# To regenerate (e.g., after recreating the kind cluster):
#   ./scripts/seal-keycloak-secrets.sh
###############################################################################
HEADER

echo "${DB_SEALED}" >> "${OUT_FILE}"
echo "---" >> "${OUT_FILE}"
echo "${ADMIN_SEALED}" >> "${OUT_FILE}"

echo ""
echo "✓ Wrote ${OUT_FILE}"
