#!/usr/bin/env bash
###############################################################################
# seal-zylos-services-secrets.sh — SealedSecrets for the zylos-services ns.
#
# Generates manifests/zylos-services/00-gateway-sealed-secret.yaml containing
# the gateway's Keycloak client secret, sealed for the zylos-services namespace.
#
# The value MUST match the zylos-gateway client secret configured in the realm
# (sealed for the keycloak namespace by seal-keycloak-client-secrets.sh).
#
# DEV VALUE IS FOR KIND ONLY. Production credentials come from AWS Secrets
# Manager via ESO.
###############################################################################
set -euo pipefail
cd "$(dirname "$0")/.."

# Must equal GATEWAY_SECRET in seal-keycloak-client-secrets.sh.
GATEWAY_SECRET="dev_secret_gateway_2026"

OUT_DIR="manifests/zylos-services"
OUT_FILE="${OUT_DIR}/00-gateway-sealed-secret.yaml"
mkdir -p "${OUT_DIR}"

echo "==> Verifying sealed-secrets controller..."
kubectl -n sealed-secrets wait --for=condition=Available --timeout=60s \
  deploy/sealed-secrets-controller >/dev/null

command -v kubeseal >/dev/null 2>&1 || { echo "ERROR: kubeseal not installed." >&2; exit 1; }

echo "==> Generating SealedSecret zylos-gateway-secrets (namespace: zylos-services)..."
SEALED=$(kubectl create secret generic zylos-gateway-secrets \
  --namespace=zylos-services \
  --from-literal=gateway-secret="${GATEWAY_SECRET}" \
  --dry-run=client -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

cat > "${OUT_FILE}" <<HEADER
###############################################################################
# Sealed Secret: gateway Keycloak client credentials (zylos-services).
# GENERATED by scripts/seal-zylos-services-secrets.sh — do not hand-edit.
# Encrypted; safe to commit. Re-run the script if the cluster's sealing key
# is rotated or the cluster is recreated.
###############################################################################
HEADER
echo "${SEALED}" >> "${OUT_FILE}"

echo "==> Wrote ${OUT_FILE}"
