#!/usr/bin/env bash
#####################################################################################
# seal-zylos-keycloak-client-secrets.sh — generate SealedSecret for Keycloak clients.
# Generates the SealedSecret resource for all confidential Keycloak client secrets
# and routes them to the correct environment overlay (local or dev).
#####################################################################################

set -euo pipefail

# Ensure an environment parameter is passed
ENV=${1:-}
if [[ "$ENV" != "local" && "$ENV" != "dev" ]]; then
  echo "Usage: $0 <local|dev>" >&2
  echo "Example: $0 local" >&2
  exit 1
fi

NS="platform"
TARGET_DIR="components/keycloak/overlays/${ENV}"
OUT_FILE="${TARGET_DIR}/zylos-keycloak-client-secrets.yaml"

mkdir -p "$TARGET_DIR"

echo "==> Verifying sealed-secrets-controller in ${ENV} cluster..."
if ! kubectl -n sealed-secrets get deploy sealed-secrets-controller >/dev/null 2>&1; then
  echo "ERROR: sealed-secrets-controller not found. Ensure your kubectl context is pointed to your ${ENV} cluster." >&2
  exit 1
fi

if ! command -v kubeseal >/dev/null 2>&1; then
  echo "ERROR: kubeseal CLI not installed." >&2
  exit 1
fi

if [[ "$ENV" == "local" ]]; then
  echo "==> Using stable reproducible secrets for [LOCAL] environment..."
  WEB_STOREFRONT_SECRET="dev_secret_web_storefront_2026"
  WEB_ADMIN_SECRET="dev_secret_web_admin_2026"
  MOBILE_BFF_SECRET="dev_secret_mobile_bff_2026"
  GATEWAY_SECRET="dev_secret_gateway_2026"
else
  echo "==> Generating strong random secrets for [DEV] environment..."
  WEB_STOREFRONT_SECRET="$(openssl rand -hex 16)"
  WEB_ADMIN_SECRET="$(openssl rand -hex 16)"
  MOBILE_BFF_SECRET="$(openssl rand -hex 16)"
  GATEWAY_SECRET="$(openssl rand -hex 16)"
fi

echo "==> Generating and sealing credentials..."

SEALED=$(kubectl create secret generic zylos-keycloak-client-secrets \
  --namespace="${NS}" \
  --from-literal=web-storefront-secret="${WEB_STOREFRONT_SECRET}" \
  --from-literal=web-admin-secret="${WEB_ADMIN_SECRET}" \
  --from-literal=mobile-bff-secret="${MOBILE_BFF_SECRET}" \
  --from-literal=gateway-secret="${GATEWAY_SECRET}" \
  --dry-run=client -o yaml | \
  kubectl annotate -f - --local "argocd.argoproj.io/hook=PreSync" -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

cat > "${OUT_FILE}" <<HEADER
###############################################################################
# Sealed Secret for Zylos Keycloak client credentials.
#
# GENERATED by scripts/seal-zylos-keycloak-client-secrets.sh — do not hand-edit.
# ENVIRONMENT: ${ENV^^}
#
# Decrypts to a Secret named zylos-keycloak-client-secrets. Consumed by
# Keycloak Realm Import configurations.
###############################################################################
HEADER

echo "${SEALED}" >> "${OUT_FILE}"

echo "✓ Success! Wrote ${OUT_FILE}"
