#!/usr/bin/env bash
set -euo pipefail

ENV=${1:-}
if [[ "$ENV" != "local" && "$ENV" != "dev" ]]; then
  echo "Usage: $0 <local|dev>" >&2
  echo "Example: $0 local" >&2
  exit 1
fi

NS="opa"
TARGET_DIR="components/platform/opa/overlays/${ENV}"
OUT_FILE="${TARGET_DIR}/opa-ghcr-secret.yaml"

mkdir -p "$TARGET_DIR"

echo "==> Verifying sealed-secrets-controller in ${ENV} cluster..."
if ! kubectl -n sealed-secrets get deploy sealed-secrets-controller >/dev/null 2>&1; then
  echo "ERROR: sealed-secrets-controller not found. Verify your current kubectl context." >&2
    exit 1
fi

if ! command -v kubeseal >/dev/null 2>&1; then
  echo "ERROR: kubeseal CLI not installed." >&2
  exit 1
fi

echo "==> Generating SealedSecret ghcr-opa-token (namespace: opa)..."

SEALED=$(kubectl create secret generic ghcr-opa-token \
  --namespace="${NS}" \
  --from-literal=token="${OPA_GHCR_TOKEN:?set OPA_GHCR_TOKEN (read:packages)}" \
  --dry-run=client -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml | \
  kubectl annotate -f - --local "argocd.argoproj.io/hook=PreSync" -o yaml)

cat > "${OUT_FILE}" <<HEADER
###############################################################################
# Sealed Secret: OPA GHCR Read Bundle Credentials.
#
# GENERATED by scripts/seal-opa-pull-secrets.sh — do not hand-edit.
# ENVIRONMENT: ${ENV^^}
#
# This resource decrypts to a plain Secret named ghcr-opa-token
# in the ${NS} namespace.
###############################################################################
HEADER
echo "${SEALED}" >> "${OUT_FILE}"

echo "✅ Success!"
