#!/usr/bin/env bash
###############################################################################
# seal-keycloak-client-secrets.sh — generate SealedSecret for Keycloak clients.
#
# Generates manifests/keycloak/06-config-cli-sealed-secrets.yaml containing
# the SealedSecret resource for all confidential Keycloak client secrets.
#
# DEV VALUES BELOW ARE FOR KIND CLUSTERS ONLY. Production credentials come
# from AWS Secrets Manager via ESO (separate path).
###############################################################################

set -euo pipefail

cd "$(dirname "$0")/.."

# Dev-only client secrets. Stable across team members for kind reproducibility.
# Pattern: dev_secret_<client>_2026
WEB_STOREFRONT_SECRET="dev_secret_web_storefront_2026"
MOBILE_BFF_SECRET="dev_secret_mobile_bff_2026"
GATEWAY_SECRET="dev_secret_gateway_2026"
INTERNAL_HELLO_SECRET="dev_secret_internal_hello_2026"
INTERNAL_CALLER_SECRET="dev_secret_internal_caller_2026"
WEB_ADMIN_SECRET="dev_secret_web_admin_2026"

OUT_FILE="manifests/keycloak/06-config-cli-sealed-secrets.yaml"

echo "==> Verifying sealed-secrets controller..."
if ! kubectl -n sealed-secrets get deploy sealed-secrets-controller >/dev/null 2>&1; then
  echo "ERROR: sealed-secrets-controller not found." >&2
  echo "Ensure PR-A.1 has been merged and Argo CD has reconciled." >&2
  exit 1
fi

kubectl -n sealed-secrets wait --for=condition=Available --timeout=60s \
  deploy/sealed-secrets-controller >/dev/null

if ! command -v kubeseal >/dev/null 2>&1; then
  echo "ERROR: kubeseal CLI not installed." >&2
  echo "See https://github.com/bitnami-labs/sealed-secrets/releases" >&2
  exit 1
fi

echo "==> Generating SealedSecret for Keycloak client credentials..."

SEALED=$(kubectl create secret generic zylos-keycloak-client-secrets \
  --namespace=keycloak \
  --from-literal=web-storefront-secret="${WEB_STOREFRONT_SECRET}" \
  --from-literal=mobile-bff-secret="${MOBILE_BFF_SECRET}" \
  --from-literal=gateway-secret="${GATEWAY_SECRET}" \
  --from-literal=internal-hello-secret="${INTERNAL_HELLO_SECRET}" \
  --from-literal=internal-caller-secret="${INTERNAL_CALLER_SECRET}" \
  --from-literal=web-admin-secret="${WEB_ADMIN_SECRET}" \
  --dry-run=client -o yaml | \
  kubeseal --controller-namespace=sealed-secrets --format=yaml)

cat > "${OUT_FILE}" <<HEADER
###############################################################################
# Sealed Secret for Keycloak client credentials.
#
# GENERATED by scripts/seal-keycloak-client-secrets.sh — do not hand-edit.
#
# Decrypts to a Secret named zylos-keycloak-client-secrets containing the
# secrets for each confidential client. Consumed by the keycloak-config-cli
# Job via env-var references with optional: true flag.
#
# Per ADR 0007: Sealed Secrets for kind dev; ESO + AWS Secrets Manager for
# production. Re-generate after kind cluster recreation:
#
#   ./scripts/seal-keycloak-client-secrets.sh
###############################################################################
HEADER

echo "${SEALED}" >> "${OUT_FILE}"

echo ""
echo "✓ Wrote ${OUT_FILE}"
echo ""
echo "Next steps:"
echo "  git add ${OUT_FILE}"
echo "  git commit -s -m 'feat(keycloak): add SealedSecret for client credentials'"
