###############################################################################
# Istio: base CRDs and cluster roles. MUST be installed before any other
# Istio component. Sync wave -10 ensures it goes early.
###############################################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: zylos-platform
    app.kubernetes.io/component: service-mesh
spec:
  project: platform
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.24.3
      helm:
        releaseName: istio-base
        valueFiles:
          - $values/helm-values/istio/base.yaml
    - repoURL: https://github.com/zylos-platform/zylos-platform-bootstrap.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # Pre-created by namespaces app
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
