apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: valkey-auth-secret
  namespace: zylos-data-valkey
spec:
  encryptedData:
    password: AgBS8AZT9/qYEHszr5/CFfwbCZ7UFxnx0ubsqBGHKsktUWSSJSfErf1GgCeh7OKpInS4cLGh3iKHgt8X5l7GaEphyzYunqNmue/Gj+IJiTFbNd4PKzNd2cXenYLK2zNcoAg0+y/8pKYYNuQqyObaXbkv9Sf51JlHt3tN9dUlZf5fNtCk/5umgQ4dIVI1N0HjkzysxSWh6j5aMReHEraL57tIEXFcdmJ0I71HzALer8oydYH71FjWV9DW4/lcXob8d89eaV4G5qO6r2CAaURvQ8mt3Qf8YtNtzyK5NYdcRk5EdjCvgHeOxKvA8VElcq6xAPQL4UJ1NCTjVUURMXze3sy3uHRo6gvg4NlFPNE1Ja6444hj41bwjYApo35WGVCPrpD+lDqhJBkClHi4X4KSN3l2gRzXrwNTisOepEiaGZkSl7w0sEjxypspXULxAuTlo+8uGeP9GnLw/thA5hdtn0cYQR5TAOLJF8vWsNJBHMABp7WOdEfY5CFhWbBWI+u7WLSUuOJ+BHmUC3sXBg3sJDYSlsNb3/NUTXw7Md932s6ln1vWc2CrDx3Yju72noaekrc/EWFH16G/aHPFu+hPR0dXAAXK3iH+PxkcGf6KlzZXQdDvPH8PkO3s53SUgmx8a2my8FtYNeW+7yQQHaBgAKHz+kcHWodYKbie2ErD6jXRwu18bUSPHt1ECFT9UYBc+/sbK0RqtuLdHZ4qNovFQcyoXUpr67dj
  template:
    metadata:
      name: valkey-auth-secret
      namespace: zylos-data-valkey
