apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: valkey-auth-secret
  namespace: zylos-data-valkey
spec:
  encryptedData:
    password: AgBZ2uqrvQg5PXWhzMXSJ/mnLtBgM0C1V8r+U254qljPX+JadjfABqWOFP3F2umKumhLem41mkvd3W3R2JkJOqn8WcIfSRr5K5NjVjC4+NAlQmSNWSOtsMgHxAfObaxZwgfr7x+jf6L0UoGNz85OBOzXQ9/tx6kzbgzJNXdnpoMbvmA2ZRRBpqotDLSs2vRsMxUdFToPWKP3RVfSw8vJYOHTFIrzCkFwisyKcymBmBC0SJlBZtBYNWoMJKZBQSEBhdYbWsRTGg4Fwyk0ILEUvaLj396ILLCA2dWAwpiHKfgCs4tplKddVSG+ZGqogj7KzkuUrHLbVRfdfXqTY0fgQLzAuIdjXH/ea/XmmgfbyUm6jBRTtdV3yvyusIc/LiTfsWdeRWKwiHj+iXenwVqdHR7nPVM/WRNfVJDHT/yL7rKCeTN4fNkvJdpDriqtT/8NolPJ+sL5tPZdcpXkNmemcgbMPzzzTSr+bxeT32Rip8FbKrc/N+FnemBRQuK2igGSBe1uraskT+UHViX/+5mmOO7hmPp9t12H1j50g0Awj3j3OEUovdxqsJEIikl8vPTLmG/xT9Rp4kotyExmDqlEqJARODBlLSm0KG4kiX5mIU1n807wTl+cNAfhZiJtOakdz7qkTq+cBsLgFNuWnk3Vte0y0Xn1rz1J2TOg66kE5RyvNNWRnEUOlimU7ujNmwreszd9k0Vylhz3nAL8V9Qoz9V3SRxz7cmz
  template:
    metadata:
      name: valkey-auth-secret
      namespace: zylos-data-valkey
