apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: valkey-auth-secret
  namespace: zylos-data-valkey
spec:
  encryptedData:
    password: AgAYqRKeeduydh18tQ9ksCZujM1oBYonxc23WPevWIrkl69mKWg6Nf7DBMLebYl3XAQ38GLvrvWp2vX08YAWxfka1j3CaxZprdcyqjyy7QQQtZ7uDO0nCPqU3fG3JvShM+8a5J41JtngC0IFTqMyepB7B2ipd7or8EfR36yJ9D9JqVJTMzgzkRNQicOP7H7nmWPbceJx1MkyukTWApiGRGWU1N2p8/xakbdZd1j+hpymQo7JmxBDskG0lc6y7sgZOT4rvuR5B7hBwjNw++1S2n9nsxBL/LOkxxWVbOsNu+DYwL4IwEEm7ak/ZcktkliWPwyhE8pc4jxKxxIoMKNa4cSmPhLKVMqeqoKV8pEPiE74cN3nsryn00MpGOBTcB7pAekEvbKT9hLSaD1u7aUjdpaUnIzIxOxcFtkm7hDSGrCk6ydMSrT07jNaUHRcj7P+QhaTO5jUyrc097O6/dlCNL8K3F4XsNfLAIRpWv/xiT5vUx9wXiO2PfJ3jmL4TDQHKgzx3lIg+WVlQVIYM4OYgQvr1aactFyZVecfA9gXlrd/BmmM01gslg42OULU5/mBGq9PpULffRyFJnDZyUratHWeWjkrxoh8UDdtrI1CuGqJQ91RO2q5aLesgClEYMx/4WuY23bL1BEQdWSRwHT3pkwlzqFl7vNCbLcSbCfY8NMa+EYeTNxgCCaq04ZR4NxEheWza5Gquw27r5idW7aCr1nbAXxYmUf0
  template:
    metadata:
      name: valkey-auth-secret
      namespace: zylos-data-valkey
