apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgBKqJADNsELoV3XDYMj+cKaqAsMD7QfA3S7CKY7ZyWfqhSMyJhwOG05g6HQx9PdG1TzzFZ1p/FmST9rZy3qTSzXWq782qlQDoyCXDWJlxf60URjgXu1AyXH/Rb0cBM4n8ybTgIKw95g/Q0/Q9Qo9D/ufM4gTz9r9lk2rMzuopLitj0kELoeZ+Cx7F0Di3z/9Pi4RZB3oC+iXt7ZkZHlAosPSlZKKQ+mZRyu+oxXBognXLlt/0y2pld6s0691ZDvfUGoHHnuWh4Bw3l+uZuaI9eJRvjC1hp3UbtGLjESv+tFCTbi1UsgWCRK+vrJBD0dDD9CvpuuE7QxLh7EpqnhgSLj++UDnh/7tJcxmmDvVuqlyuvO2FlJG9spyWs3EIZdKtuSzVd3cVLYcmaeRoI/xLdVX/6+D0inuNJig55QiPkr6naaXQ8oaCwPo8jwVDx7PtD4BHZYR0x7P1cME8AjJWQhDylhhpiYrGNkGVxGBbLiMqE3Cte36bid3c/+Ngo8/K5cb8rAS47NWvIK3pcacfU4iCnN39HGUEt226kd0sYQS431/p3lFLzM5JgIiLQcCaarLWh71LA4mas/GkkQPc28DJ8aGI7/beeUBwO0zEMpM1/jarr9TCnZ4iqWp9C1yCIcy5d72S8wVI9G3RLQyEGHHKBsy2RHhgZfGyn7GncGC407uoF15GyC2N9vO827PWPmSS2i5TndM9U88w0KrPb0uA==
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-data-opensearch
