apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgDHrgv7QLs6GlGz7ym6tZXUMdnyU1yTKKbDhR+ag7aNz315vJQ+pGXAJHwLoOMPFqNGmh4v6nK3npK1Bex0VZzHln8x2wtoILu9CYoxq3n5UG635RAZ1t1hkZ6dROjVLoaygdEvgwtXgrvVgbrMv5/ywhYQ1Z4skwxEDRCuVPqimYu31y/hTpfiNHpku4sDlxH0RHBIvyenSAxIM4gjtINRT6JE/bKIqPX2x4/6zpdlxmy6qM7Pxy0rYhXQIOM/mcjhznfO2VYjsePMbvtj66fOO5W4QBK3eTz2EQQ1AwA9RGq2175zibm0LxI79SjkjEUVFsUZp3X7yqVZbAayABbYfgThP+I3viM5HSAF3UfFtT/17ee5pBkGx7xdaswSOGI5ijLd1TP8w9sUgCG0cc/+ur498wV3/Y9lWYPiCvAbggJNH9mxcOXmgbeHwgAHp0dPvvx+tyDMZyVG8ggKkW7yQW4Ps6dLBxJVBv6FTjeQcGSWTFMx1hL2Gu99xasLitbWZDo3Fy3cr/knLuZkIt2o2yLiaHX1TurQYbk5xOweLc57u6rBq/KMlXYRBRZSVoAe8Gy+D1XaE965vdbRw8/LC5QleAZjV235pJrfH2LpH1LFxOlMb46C3N8f63da6s86xYDfoQAP+yWX19+pvw4M1bCIXOFV2UPzw+PcS1N4t61foraRqD5bqOaxVrXfaJ6t94CAfBUkf/L8lWh75c6u8g==
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-data-opensearch
