apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: catalog-opensearch-app-user
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgAqUCNNXjRRRIAAVSUfyERGhKw7JYQhUGba2P4gkG7SHlzLE5WSPcQZq7Y1qZLk5mo0ClwBJ//t3Eroga0TLEC3FI3TWd8o9La4bJqf/A5MPWQCj970UThI0y3Uuc7NYbE1eH1fymBX0bgh7VitwZeKx8knbcg5FO1vhzaieWebUzGB7egA/rTik4GICUQyDQmCwJz+BEif/erkinrd7YF2KZRwj7kZ+VGh31m36rBctaQ1/yAQf+CxEAQcTsKXfli5lOh2a8+5dyjCAL6Wx/o9o/PqomMBhrx/GlXYAo8iuhU1HRvPWC8X7iVOWSNVrwX0lJDn3FWdsSme7YPdvTS18UDKqBPCqCeVOhHOEqfWDuFQyw0o8oEPLcLaMEB38nyDfXVDI9vHf0rVXe31+HknF8ZEdr1UBrew3Mnz8tBxjkeHY3d/CF7YwZ+GXBdaXCrxDr1Z/oVtcCNU71K+4iXKihhqrZY7gYRiWRmmQChdWLWLwVVI8NVCObg+qZVB/jIydsMsHC0HFTYDL4om7upZKZ4tcgWQRWiBYeI+sxHRlaf4UnV/cBZ4bddtybu08YIsc3MI/7nLgmV5HYCdiH/chetaHs1R390Dp3nOFuRKWhutfYjSSEtPaU7n60p7pp6Lg14GdMk4qYCWl7UZPuffftxvWau6v9tOyL8YYY8wdJbkSiNE6SYYm+RCrU7SUTAjjgqpEuug242wrxnRUVf3zQ==
  template:
    metadata:
      name: catalog-opensearch-app-user
      namespace: zylos-data-opensearch
