apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: opensearch-admin-credentials
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgCBZB2NosFogWhGCMZd2vpEhPUMZCBxln0Pas0IFj/eHrsH0O9QF3OYRxno/SdxvfO78kGl3guP5uk2iEUpvQroMnFRfHBt1njFZtbG9MG9w1gBlZmVWkzeaJyODenCvKjMP/nZfyHQ+7fALZgJyZ5fNdnfTC/x1vmVLrHMDf9ErRHCPHA3OVc97fl/0jDDI4zJBExoOTT5QHcLeZyQpEafRp8zqRA9+Ag3jkDF62O9f11Cr/VBshhe4+/tdkC/t3HjdlcirPLNWXxyp8XIDGmf/nnylB2Qo3NMQYP7oc0yE+2JRzviI6YhFwOnXpe+oePoZTzxHvRtFRU5qC4FcdM0S+PRiSigZNnIUNxyxeGPZ9BHkzqK/IN3hrcoy638J+rxw1Iz2iiaZqXX/1Sg/Pr2HHtW/LfcgUShsYLcEzePb4H3P/tt5U70UBZ/l1h5G+RPeoNscrgk6yIYbV8zxO4GnkksBym0rSUsrm9TxYPulOKhoh4cQ4KNPEl9S0gP/LDTQw6I0zMqHypmM8ys+ifPksSp6SMVWTb5g1Xo+vgrGyIwqgpDqEj43gC++zvBj404MOrwmqo1SOcqGbzKQmZ4eL8k8VdGbk6UahzprGTGTS0bEHoLI/8pnzO9M/jmDzpVniL/Y999HT+xR+4BegP6UjHDBoV6RZmyPKtj6wrpdg/iIv/xXc5OwVuWxcr0EjnruW61D5LIxu4o0ePDhq0DRic=
  template:
    metadata:
      name: opensearch-admin-credentials
      namespace: zylos-data-opensearch
