apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: opensearch-admin-credentials
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgBbpzskeR+fX8+vUsDffVLoAXkn3RMPFn0ydDF16XCzf/zj5SzMcCeaxXeWG1/+CoYxV4jljGTou3eBVVbbT2JZvO9QdT0y1Ta7wsZHq6q1yhCO4CSk65aj6Hm7qZCRdcEZ2Q/7qPZmL3Oc3boanDbkc0L3cchpiloQQTOOHBh2WypR8qvWHXXNQ+uhmQj8Tfqv9wtI3PVK/l6XF1h14Yzxq0Goy5/3Xz9Tgl42VlqJe/b80fUuA7cP8Rh+9xW7xEJb7NeuChC3OYcbC5/mq2gAn6Z8v6l6f9Er7GlqVj0HacsH6SfoI04M0/lhQExlX3bqZ3MHz1AFI6YpS2mWv8nHTD7EqxnvME/tSuJatk1N0VOw3tn4nGD2QiboVdmK73SwoqS4OjQztitfqJj9j1OP1BiCzkJShVihY3dRYr7cEenpm67H+Vq1BWHpJdfmDS5iO8pct+WuDqHQl5Xd3O5RljnycHCnESEik6pxHsInaU+1IjFShPdOMraMvcfzIP4+VF/P04MSuCvzilJ1LuT14GcEvpSmBP930UX+xfTSpq3h2Mc8BCGry0YyKX+VgouVMINR94/IddpZP/UD01EPL4CcNxtMMM2bdmMPrA3TlJbBRZULrCpZQV8FBLuFN1kIcSM0a526PFOBY+o5ytZFCVXT8KnmY7xldOIijO1MKXRXYxBQzButSDbvg3gN8SwQ1/Z7YF26UqU5oMRr3ECfUrM=
  template:
    metadata:
      name: opensearch-admin-credentials
      namespace: zylos-data-opensearch
