apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: opensearch-internal-users
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    internal_users.yml: AgAtdyc6nfJ+O6RUxlbXYkNjtYUILG0D0rlyP78nkU9hos5HhJEU76fNP2Mb9sAQYyyP66qmvSS8T5QVKkCfPo/Q8Z8ii2WTUtsmYl6k+YzjDH2xN4t0CGKTI8mOi6cyF8ip7ufsZeOWkN55mUHgbV6gy4+zcgtGUrsYZDifq+5WeCPp6rqnGvDGKbOwCKZ7T/5iGTrnwrWuI4/yxXMcab95oGWN4lyW9k6uFjoygB3SlVLiJFSJlP8mMj0IdbEAXViyO+hHjChU5FWSyaN3qGjq/pID7U3taCWH8UoLRbQOFP0nOlCB8N8zGckUUmkBMZ6jTnaM+j0St0vpofJzfMJK82eBlDWY/SJ23PpPpFFQqyRwjYVfe5Uf58aqVhNT3qqdtxsQTXs2lXZn3XWfPP6qZnVLdNnO9Oy80uCU5cKxZ5fy8OMxbIUE6PVwggR1bDLspAlHTRLTpEjj+kZSjgLNDc3+Et5VA1ChAUikm5C5jYlnKwnbFJWRatcfvlrgsHQkkiGgRjaS2zGKoqK+8EmpeF7Mr/rE+yEeTq+H83elJKzkhL/ZoFWZPkkIcb1Byc6nmyuXAgc9LX4f+Dcdyj8AdiPT9YUCZnoPsS6nxduQicqcAcW+sS0MNIwSKoJr+3i6aXLVGelHDB9u9dDdum1/S6Q+GacBx3WPg4npSmey1lPwKvkRJo2lp1LxBYbHEdvTmkXfj7wf6SzYl/UncaTcDEewfZa8SCV8z6ETp7MKok519rQvAHaoa9O359GdzXB8ttY0TdthE47E7XWtXYXmrCyftCKb7QZQfPPk2+o/5Q71yYWAww51S8w/EB3g3Q6rMsW+EEaHAsGfZOizqBKI3X1DM36tS8X+l3aMYzJLWSXxrkAfZXi6PUrSSLd+XOrLI/t8e9pBbly3aStrTjo67SlOH1eTzq/XsYYboQLQCFMPcLvcBP+6/HH0jRJ4s+U/e/mMyYUZ4qgmyF0/PQ3J+KmOSHH38v+EB4vtkseAn84NPK4jmZNZWcEhv2+V73JQiaXLOIc+5Lptl8FGeD3pmlbFNstFVnsYTN2A7tRb/Yby32gsNgBQBlGoe4cXTS1hm91WCFM27sIYLAmpgnvur7B5iBEhANISXGVaFz6h7NvPRi07z7p/t80CcCYzsevTMu9Y/SACuxZswfWfMxH0hrFBcENlUlWYAqOUqj2q4shEfyhwC8YQYFC1vhKlDBpiXK71K2aDsc7KtKtreu0/i4YdJzDkyg==
  template:
    metadata:
      name: opensearch-internal-users
      namespace: zylos-data-opensearch
