apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: opensearch-admin-credentials
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    password: AgA2IAclV+iLXf4/dfwJY+zI3kgcPBOuyDYTaKFspTD0X3Q0EXTlw57KmjyGmrRnAWkPGstmOdSPUzWi3uSbkeo8YFsmjo7sfK64oyOMVNRKFFdaHWf+fK0UIFOQwtoNjJq+TRqOThrNDuduB+JAFAcX1Yj3wA5ZqW+jJhNhhykJo94fNx6Dfh4DP02xdbAdp8DWxJf9jKmOKpBCRz1EKeW0pMR6hAaMYW1TkuGisgEmKCM/U3fVNg5HvDygQRc6GSqcxgk+uMCMmpSBAIG3aSwM/6ZT0XAgPiAR5nWDFcQI1oN+Akn8wvBPM3NzqwCkcLmtcR84H6kFKORsLk4rWjOb25Tr9vlvtKLeDpFoxeMCK9JDX6VVS28TS1Ww3KWuTmm6E1wht92boEaZ1y78hMCoOrawThVJMB4PfAVs3Eh6T5EHLD1lsYM3T1W6ETHnZzlEUOJeTEDnd6hwDRsuMHz/TLmgMoh5tcTNhczWiAniflzd+d4p2YW2p4+EaxqbynJaifVQa6BfVo03Wrbk09GeaQuHScO8Iy1KRAo2LoMUeDElBWExu6QFU01UmNB1UY73DaWBPNlKRo0MRtlNywDuu5Ej5z4jH2faZgDumwPf2vQyNXCeTPwAFtlxzaux993BobpR35NxV5H8IsfFLS4fkHTD+fU4bmKQdViznJ3rGKa2P+JOPlNYRxYkWsRrgTrfCUwjgg==
  template:
    metadata:
      name: opensearch-admin-credentials
      namespace: zylos-data-opensearch
