apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  name: opensearch-internal-users
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    internal_users.yml: AgBBiJ+g3ES9Kb1S08RduPcnHVp5lhfFCsvTwpHq7RWoyJzwRMTUJZ+C5TrwgN7GKRPd8YzbK/W+Iv1Ummjsj99nrKiVYiXnJrPvB5hygZTHSBOv20xYpb0ABTS/R/TFKtDt4khXQanyJ2Ob2ATmyf4KYYVtQubCXGbIurI+ftQR24PQaPyBhDE7v7/XK+FmoTY3z+zaNYg9Ihj3KvDuo2jOhx33k3wWMxEtMzPcSSSIsZgGzfnvEYliO/rlv2r7M+TVZrWLsZgGV1EwgLHHf86bDLT/MRxyJIaKSfBOsmZU7SS+stLbnPh8THy1mb1kqOdleZlogTTgUq2kTRfXiwB83Dzm20oNnulVnpUEqTtMTFoa0SiDXJXMS0j22yyT7T/PzEB358IFDq4GcFMcgca2ThcbHhrM2gv9Ky/nqxYg6f2dlgB6eXYlRE3T6XBWwRVs74LFFXfPuaCjZOWdmKi5XJQeq2pXEpmipnGV6K/ZhWL29cCRLwOgPeDY3GaFzHaCz3Z/j/xlYEyRwmWBQ67xcJvdKa24iSvBuiZbbr6bdMdkJeOyo1tzbrlt9Dx3//UANOy3jlOVO6//m3BF+XHKD0P1W7lsDvRJhotZm4Som/d6GmvCHqGjxOSRyawgPLlz9bKKCUgj1iNCiuQ/M8+lYx+yjqg/XY+QgUS3BhWYUSSeYc/Y40Qcd6XPd+gbm9A6jLaqxGf4rwa7/XnP3+er/M6h1UKYVO2uH4g3Lo5yOpb1WDCt1iKU8gV/pC1HKRA/vJ24guVD1UoIW1IFTtoTyPDA9sIGPs/EkSoM++d1ZVqwhddlOr30e1nC+4iGG1uY3a4WamtR4Is8G3ay7X7S4r6QiYoe/EE65QrJlzAh55L1CF/mTmxBf6FIg1RrNTJKzyL/zKBYz4IH0jUvaGGB8LlrxJYl1cATh6VG2HFhdBZgppGV6qPPzGOXq3YbZWAISHuue3us5nCkKijGSbFrhh1F0oy1Ox8hHL6CSQBySY0LVDlJqce2cNWuR5WFgOEdHCx34HYBOV2FX6zdM+3J2VIFWwVj+DEOmsi27ukpiHacYvrj/xHItiw88jRSUla7Jz7ugirmeAamSLW/h62QZHNK+ups9LRYFTvfUboo3KWcMSf+ZW0u1XcJ30z6Nxs62LMZlDUE75XC8effYQfP/3GO80EShmf+HsYvaOZTXRji0emp+7/XLC6EB/CCIeesORynkeNVa4ZEaYqcqnJa+0IIGTKZAg==
  template:
    metadata:
      name: opensearch-internal-users
      namespace: zylos-data-opensearch
