apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: opensearch-internal-users
  namespace: zylos-data-opensearch
spec:
  encryptedData:
    internal_users.yml: AgBwsUyEVbKnsWder4tXny6fDQEcqrylmJHRDBXloSnCd/iIEIJTNyLHt4e6FML5GORNnaLGfRA+qZ5htBfy8R7N6E2JqMoMI5mAkqPlFGGbP1eCezAm5NE92ql3dHFM3N9aW7GVKYx0EVIQ0ttgy2qHbk3v2oH6Q35G8TzgajgUL4RFkQAU7F9G3OyHasFYcgRyiMagEV3rTup5wF4wbajwcgdzwF/HeS7z7lH71O/yTeOmHYFA7ySOm4oY5ibm7a7zVEd/ZLfLuGoyBF1PWRnAoulW4aIKdg22hFtfSP9Fr9GSIoVSelS3+n+x6xtCYetwIJLAz2rvdYmDJHGbqxD9cGUjaloc4BAAqlfLRJC/jnDa4j3aMVuH0IRzPhLP5xaAbPoCPlmUCpjgyTfjc37TpT91OaGl/5gNQc555K2Cyo83haaphtAkics6sOUdQWMvaKfGdCpVZC1ONSEW+d6P/Qyz/9weBWuWCxBWhgQAMAdDeVWnTip8RoIk2i0N+LzyqXIlS/nLcrgAOedDUC3spv1RZaWPHWH1w/vGVzb8XUK/56HJi3jhrUv+0i6AblWuKbk2nq6jm0rlI+vJAj8WPdxwuR2EPe/FDejXUMW6+0Mb13j+ert+U5HODGuJKwzfyGYYPHn9U6epyuDGBqHzf4sJrgoquGwEKKJusPKdCIvhWtMUfzJquzXOThWprTeeWNnFrqgAn7M7/aaA3g1txnTfo39EpQ+3FDRN224y+SeFWi3/Ob0o4rELLWaKXvqMSBViIdgbb7xCHpd/iDapAsVuGSS1UVAu43q1A9r4J7qAWmNkIeJdQMzJWF7ioqCbe1myPMl9WRyyjuyDzfpSjVIGa7He+dJqx+7R5Or8+8J3lB2FrmA8ZiiS+PETmjRWCwOWJcONi9rxCz4yfjHCsQwNQhthwFOM2E4IealbzSaZb+ryLaSYXczh3xgxiufIxe3aR17v8y7HUuhMNi6Sfk12maL4VvtM3tWEj/K9jARQiHefI1ivbO90mGLuxrfYvTXf4pIJ/hWxtZpi+Iypc73XxFe0h5NpZgVNpXjbSSxj0wTMNCEhDgZHaxwTHFDqKUmuacBnl1VDNaK+auCXEwGiXbvVpT7fun48csCSbGexHlKatSL2/8kaetsDntUkWYV+KdZxc9qyASyovziOmBBIh17rKa9kKcqnC9e0tBHaLWnnfs9v9ZeGKcNtiX3RE9+syzBTCPcUWFQB8WyKowQ2INbVFA==
  template:
    metadata:
      name: opensearch-internal-users
      namespace: zylos-data-opensearch
