apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: zylos-kafka
  namespace: zylos-data-kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    # version omitted -> operator's default
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}

---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual
  namespace: zylos-data-kafka
  labels:
    strimzi.io/cluster: zylos-kafka
spec:
  replicas: 1
  roles:
    - controller
    - broker
  resources:
    requests:
      cpu: 250m
      memory: 768Mi
    limits:
      cpu: 1
      memory: 1536Mi
  jvmOptions:
    -Xms: 512m
    -Xmx: 512m
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
